// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:collection/collection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `validate_fit_target`

I32Array20 get canFitGroupAttrIds => RustLib.instance.api
    .crateApiValidatePreValidateFitTargetCanFitGroupAttrIds();

I32Array11 get canFitTypeAttrIds => RustLib.instance.api
    .crateApiValidatePreValidateFitTargetCanFitTypeAttrIds();

class I32Array11 extends NonGrowableListView<int> {
  static const arraySize = 11;

  @internal
  Int32List get inner => _inner;
  final Int32List _inner;

  I32Array11(this._inner)
      : assert(_inner.length == arraySize),
        super(_inner);

  I32Array11.init() : this(Int32List(arraySize));
}

class I32Array20 extends NonGrowableListView<int> {
  static const arraySize = 20;

  @internal
  Int32List get inner => _inner;
  final Int32List _inner;

  I32Array20(this._inner)
      : assert(_inner.length == arraySize),
        super(_inner);

  I32Array20.init() : this(Int32List(arraySize));
}
