// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../../../frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `validate_slot_num`

int get effectLauncher => RustLib.instance.api.crateApiValidatePreValidateSlotNumEffectLauncher();

int get effectTurret => RustLib.instance.api.crateApiValidatePreValidateSlotNumEffectTurret();

int get attrTurret => RustLib.instance.api.crateApiValidatePreValidateSlotNumAttrTurret();

int get attrLauncher => RustLib.instance.api.crateApiValidatePreValidateSlotNumAttrLauncher();

int get attrSubsystemTurret =>
    RustLib.instance.api.crateApiValidatePreValidateSlotNumAttrSubsystemTurret();

int get attrSubsystemLauncher =>
    RustLib.instance.api.crateApiValidatePreValidateSlotNumAttrSubsystemLauncher();
