[localizations]
default = "en"
supported = ["en", "zh"]

[localizations.translation]
en = "English"
zh = "简体中文"

[paths]
log = "data/log"

[resources.example]
descriptor = "data/resources/example/descriptor.toml"

[resources.tranquility]
descriptor = "data/resources/tranquility/descriptor.toml"

[resources.serenity]
descriptor = "data/resources/serenity/descriptor.toml"
