{
  description = "Development shell for EVE Fit Assistant";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs =
    { nixpkgs, ... }:
    let
      system = "x86_64-linux";

      pkgs = import nixpkgs {
        inherit system;
        config = {
          allowUnfree = true;
          android_sdk.accept_license = true;
        };
      };

      androidComposition = pkgs.androidenv.composeAndroidPackages {
        includeCmake = true;
        includeEmulator = false;
        includeNDK = true;
        includeSystemImages = false;
        platformVersions = [
          "33"
          "34"
          "35"
          "latest"
        ];
        buildToolsVersions = [ "latest" ];
        cmakeVersions = [ "latest" ];
        ndkVersions = [
          "27.0.12077973"
          "28.0.13004108"
          "29.0.14206865"
        ];
      };

      androidSdk = androidComposition.androidsdk;
      gccRuntimeLibraryPath = pkgs.lib.makeLibraryPath [ pkgs.stdenv.cc.cc ];
      inherit (pkgs)
        flutter
        jdk17
        python3
        ;
    in
    {
      devShells.${system}.default = pkgs.mkShell {
        packages = with pkgs; [
          androidSdk
          androidComposition.platform-tools
          flutter
          jdk17
          uv
          python3
          rustup
          rustc
          cargo
          rustfmt
          clippy
          rust-analyzer
          pkg-config
          cmake
          ninja
          clang
          llvmPackages.libclang
          protobuf
          protoc-gen-dart
        ];

        LANG = "C.UTF-8";
        LC_ALL = "C.UTF-8";
        JAVA_HOME = jdk17.home;
        ANDROID_SDK_ROOT = "${androidSdk}/libexec/android-sdk";
        ANDROID_HOME = "${androidSdk}/libexec/android-sdk";
        ANDROID_NDK_ROOT = "${androidSdk}/libexec/android-sdk/ndk-bundle";
        NDK_HOME = "${androidSdk}/libexec/android-sdk/ndk-bundle";
        UV_PYTHON = "${python3}/bin/python3";
        UV_PYTHON_DOWNLOADS = "never";
        LIBCLANG_PATH = "${pkgs.llvmPackages.libclang.lib}/lib";

        shellHook = ''
          export LD_LIBRARY_PATH="${gccRuntimeLibraryPath}''${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

          aapt2_path="$(echo "$ANDROID_SDK_ROOT/build-tools/"*"/aapt2")"
          export GRADLE_OPTS="-Dorg.gradle.project.android.aapt2FromMavenOverride=$aapt2_path''${GRADLE_OPTS:+ $GRADLE_OPTS}"

          cmake_root="$(echo "$ANDROID_SDK_ROOT/cmake/"*/)"
          export PATH="$cmake_root/bin:$PATH"

          local_properties="android/local.properties"
          marker="# Generated by nix develop from flake.nix"

          if [ ! -f "$local_properties" ] || grep -Fqx "$marker" "$local_properties"; then
            printf '%s\n' \
              "$marker" \
              "flutter.sdk=${flutter}" \
              "sdk.dir=$ANDROID_SDK_ROOT" \
              "ndk.dir=$ANDROID_NDK_ROOT" \
              "cmake.dir=$cmake_root" \
              > "$local_properties"
          fi
        '';
      };
    };
}
