[project]
name = "eve-fit-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.11.12",
    "case-convert>=1.1.0",
    "pillow>=11.1.0",
    "protobuf>=5.29.3",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
]

[tool.uv.workspace]
members = ["data/convert", "data/bundle", "data/render"]
