-- Platform posts: the publication of a fit at a point in time, owned by
-- efa-platform-api. Joins into fits by fit_hash (no FK: cross-ownership;
-- integrity is guaranteed by the submit orchestration).
-- See docs/temp/api-unit/spec.md §4.2.
--
-- Migration filenames must never collide with efa-platform-fit-storage's
-- (`0001_init.sql` there) — wrangler records applied filenames per database.

CREATE TABLE posts (
    post_id TEXT PRIMARY KEY,              -- UUID v4, generated by efa-platform-api
    fit_hash TEXT NOT NULL,                -- join key into fits; no FK (cross-ownership)
    fit_name TEXT NOT NULL,                -- denormalized from FitSnapshot.header.fit_name
    description TEXT NOT NULL,             -- preview of FitSnapshot.header.description (≤ 280 code points)
    ship_names TEXT NOT NULL,              -- JSON map locale -> name, from FitSnapshot.ship.type.names
    ship_type_id INTEGER NOT NULL,         -- denormalized from FitSnapshot.ship.type.type_id
    last_modified_ms INTEGER NOT NULL,     -- denormalized from FitSnapshot.header.last_modified_ms
    generator TEXT,                        -- nullable, from FitSnapshot.header.generator
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX posts_fit_hash ON posts (fit_hash);
CREATE INDEX posts_created_at ON posts (created_at DESC, post_id DESC);
