-- Platform accounts: email+password users and their refresh-token sessions,
-- owned by efa-platform-api. OTPs and rate-limit counters live in the AUTH_KV
-- namespace (TTL-bound data); sessions live only here so rotation and reuse
-- detection see strongly-consistent state.
--
-- Migration filenames must never collide with the other workers sharing this
-- database (`0001_init.sql` in efa-platform-fit-storage, `0001_posts.sql` and
-- `0002_ship_filter.sql` here) — wrangler records applied filenames per
-- database.

CREATE TABLE users (
    user_id       TEXT PRIMARY KEY,                 -- UUID v4, generated by efa-platform-api
    email         TEXT NOT NULL UNIQUE,             -- lowercase-normalized
    password_hash TEXT NOT NULL,                    -- "pbkdf2$<iter>$<salt_b64>$<hash_b64>"
    status        TEXT NOT NULL CHECK (status IN ('pending','active','deregistered')),
    token_version INTEGER NOT NULL DEFAULT 0,       -- global invalidation (reset/deregister)
    created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE auth_sessions (
    session_id   TEXT PRIMARY KEY,                  -- UUID v4
    user_id      TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    refresh_hash TEXT NOT NULL UNIQUE,              -- SHA-256 hex of the opaque refresh token
    created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    expires_at   TEXT NOT NULL,
    revoked_at   TEXT,                              -- set on logout/reuse-revoke
    replaced_by  TEXT,                              -- session_id of the rotation successor
    rotation_grace_until TEXT,                      -- grace window for idempotent replay of
                                                    -- the previous token after rotation (~60 s)
    user_agent   TEXT,
    ip           TEXT
);
CREATE INDEX auth_sessions_user ON auth_sessions(user_id);
CREATE INDEX auth_sessions_expiry ON auth_sessions(expires_at);
