-- Post ownership: every post carries the uploading account's user id.
-- posts is owned by efa-platform-api.
-- author_id is nullable: NULL is the tombstone marker meaning
-- "this post is referenced by a deleted (or pre-auth legacy) user".
-- ON DELETE SET NULL guarantees posts survive a hard user delete.
--
-- Migration filenames must never collide with the other workers sharing this
-- database (`0001_init.sql` in efa-platform-fit-storage) — wrangler records
-- applied filenames per database.

CREATE TABLE posts_new (
    post_id TEXT PRIMARY KEY,              -- UUID v4, generated by efa-platform-api
    author_id TEXT REFERENCES users(user_id) ON DELETE SET NULL,  -- NULL = deleted-user tombstone
    fit_hash TEXT NOT NULL,                -- join key into fits; no FK (cross-ownership)
    fit_name TEXT NOT NULL,
    description TEXT NOT NULL,             -- preview, <= 280 code points
    ship_names TEXT NOT NULL,              -- JSON map locale -> name
    ship_type_id INTEGER NOT NULL,
    last_modified_ms INTEGER NOT NULL,
    generator TEXT,                        -- nullable
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- Migrate legacy anonymous posts: they keep every column; author_id becomes NULL (tombstone).
INSERT INTO posts_new (post_id, author_id, fit_hash, fit_name, description,
                       ship_names, ship_type_id, last_modified_ms, generator, created_at)
SELECT post_id, NULL, fit_hash, fit_name, description,
       ship_names, ship_type_id, last_modified_ms, generator, created_at
FROM posts;

DROP TABLE posts;
ALTER TABLE posts_new RENAME TO posts;

CREATE INDEX posts_fit_hash ON posts (fit_hash);
CREATE INDEX posts_created_at ON posts (created_at DESC, post_id DESC);
CREATE INDEX posts_ship_created ON posts (ship_type_id, created_at DESC, post_id DESC);
CREATE INDEX posts_author ON posts (author_id);   -- fast per-author scanning
