-- Post discussion comments: flat, chronological markdown messages on a post
-- thread (the post itself is the titled thread). Owned by efa-platform-api;
-- posts and users are owned by the same worker, so real FKs apply.
-- ON DELETE CASCADE removes a post's comments with it; ON DELETE SET NULL
-- keeps comments of a hard-deleted user as tombstones (same pattern as
-- posts.author_id in 0004_post_author.sql).
--
-- Migration filenames must never collide with the other workers sharing this
-- database (`0001_init.sql` in efa-platform-fit-storage and
-- efa-platform-data-sync) — wrangler records applied filenames per database.

CREATE TABLE comments (
    comment_id TEXT PRIMARY KEY,              -- UUID v4, generated by efa-platform-api
    post_id    TEXT NOT NULL REFERENCES posts(post_id) ON DELETE CASCADE,
    author_id  TEXT REFERENCES users(user_id) ON DELETE SET NULL,  -- NULL = deleted-user tombstone
    body       TEXT NOT NULL,                 -- raw markdown (length capped by the API)
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX comments_post_created ON comments (post_id, created_at, comment_id);
