from __future__ import annotations

from typing import TYPE_CHECKING

from caseconverter import camelcase

from data.lib.constant import ASSETS_OUT_PATH
from data.lib.constant import ASSETS_ROOT
from data.lib.constant import PROJECT_ROOT


if TYPE_CHECKING:
    from pathlib import Path


def codegen_dart() -> list[Path]:
    assets_dir = PROJECT_ROOT

    with ASSETS_OUT_PATH.open("w", encoding="utf-8") as f:
        f.write(
            "// Automatically generated by `lib.codegen.asset.codegen_dart`\n"
            "// DO NOT EDIT\n\n"
            'part of "assets.dart";\n\n'
        )

        f.write("class Assets {\n")

        for any_file in ASSETS_ROOT.rglob("*"):
            if any_file.is_file():
                relative_path = any_file.relative_to(assets_dir).as_posix()
                variable_name = camelcase(any_file.stem)
                f.write(
                    f'  static const BundleKey {variable_name} = BundleKey("{relative_path}");\n'
                )

        f.write("}\n\n")

        f.write("class ImageAssets {\n")

        for any_file in (ASSETS_ROOT / "images").rglob("*"):
            if any_file.is_file():
                relative_path = any_file.relative_to(assets_dir).as_posix()
                variable_name = camelcase(any_file.stem)
                f.write(
                    f"  static const ImageProvider {variable_name} ="
                    f' AssetImage("{relative_path}");\n'
                )

        f.write("}\n")

    return [ASSETS_OUT_PATH]
