from __future__ import annotations

import json

from typing import TYPE_CHECKING

from data.lib.constant import EVE_ATTR_OUT_PATH
from data.lib.constant import PROJECT_ROOT


if TYPE_CHECKING:
    from pathlib import Path


def codegen_dart() -> list[Path]:
    out_file = EVE_ATTR_OUT_PATH
    native_output_file = (
        PROJECT_ROOT
        / "data"
        / "resources"
        / "tranquility"
        / "cache"
        / "native"
        / "json"
        / "dogmaAttributes.json"
    )
    out_file.parent.mkdir(exist_ok=True, parents=True)

    with open(native_output_file, "r", encoding="utf-8") as f:
        native_attrs = json.load(f)

    with open(out_file, "w+", encoding="utf-8") as f:
        f.write(
            "// Automatically generated by `lib.codegen.attr_id.codegen_dart`\n"
            "// DO NOT EDIT\n\n"
            'part of "eve.dart";\n'
        )

        f.write("class EveConstExtendedAttrID {\n")

        for key, value in native_attrs["entries"].items():
            if int(key) >= 0:
                continue

            f.write(f"  /// - Name: {value['name']}\n")
            f.write(f"  /// - High is good: {value['highIsGood']}\n")
            f.write(f"  static const int {value['name']} = {key};\n")

        f.write("}\n\n")

    return [out_file]
