from __future__ import annotations

from typing import TYPE_CHECKING

import data.lib.config

from data.lib.constant import DART_ROOT


if TYPE_CHECKING:
    from pathlib import Path


OUT_PATH = DART_ROOT / "storage" / "bundle" / "schema_version.dart"


def codegen_dart() -> list[Path]:
    data.lib.config.ProjectConfiguration.ensure_loaded()
    bundle_schema = data.lib.config.CONFIGURATION.bundle_schema
    current = bundle_schema.current
    supported = bundle_schema.supported
    supported_str = ", ".join(str(v) for v in supported)

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUT_PATH.open("w", encoding="utf-8") as f:
        f.write(
            "// Automatically generated by `lib.codegen.bundle_schema.codegen_dart`\n"
            "// DO NOT EDIT\n\n"
            'import "package:fast_immutable_collections/fast_immutable_collections.dart";\n\n'
            f"const int currentBundleSchemaVersion = {current};\n"
            f"final IList<int> supportedBundleSchemaVersions = IList([{supported_str}]);\n"
        )

    return [OUT_PATH]
