from __future__ import annotations

from typing import TYPE_CHECKING

import data.lib.config

from data.lib.constant import DART_ROOT


if TYPE_CHECKING:
    from pathlib import Path


OUT_PATH = DART_ROOT / "storage" / "bundle" / "schema_version.dart"


def codegen_dart() -> list[Path]:
    data.lib.config.ProjectConfiguration.ensure_loaded()
    bundle_schema = data.lib.config.CONFIGURATION.bundle_schema

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUT_PATH.open("w", encoding="utf-8") as f:
        f.write(
            "// Automatically generated by `lib.codegen.bundle_schema.codegen_dart`\n"
            "// DO NOT EDIT\n\n"
            f"const int currentBundleSchemaVersion = {bundle_schema.current};\n"
            f"const int minSupportedBundleSchemaVersion = {bundle_schema.min};\n"
        )

    return [OUT_PATH]
