from __future__ import annotations

import re

from typing import TYPE_CHECKING

from data.lib.constant import EVE_DOGMA_UNIT_OUT_PATH
from data.lib.workspace.generate import GeneratorDatasource


if TYPE_CHECKING:
    from pathlib import Path

    from data.lib.workspace.config import WorkspaceConfig


_DART_KEYWORDS = {
    "abstract",
    "as",
    "assert",
    "async",
    "await",
    "base",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "covariant",
    "default",
    "deferred",
    "do",
    "dynamic",
    "else",
    "enum",
    "export",
    "extends",
    "extension",
    "external",
    "factory",
    "false",
    "final",
    "finally",
    "for",
    "function",
    "get",
    "hide",
    "if",
    "implements",
    "import",
    "in",
    "interface",
    "is",
    "late",
    "library",
    "mixin",
    "new",
    "null",
    "on",
    "operator",
    "part",
    "required",
    "rethrow",
    "return",
    "sealed",
    "set",
    "show",
    "static",
    "super",
    "switch",
    "sync",
    "this",
    "throw",
    "true",
    "try",
    "typedef",
    "var",
    "void",
    "when",
    "while",
    "with",
    "yield",
}


def _words(value: str) -> list[str]:
    spaced = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", value)
    return re.findall(r"[A-Za-z0-9]+", spaced)


def _upper_camel(value: str) -> str:
    if len(value) == 0:
        return value
    return value[:1].upper() + value[1:].lower()


def _enum_name(name: str, unit_id: int) -> str:
    parts = _words(name)
    if len(parts) == 0:
        return f"unit{unit_id}"

    candidate = parts[0].lower() + "".join(_upper_camel(part) for part in parts[1:])
    if candidate[0].isdigit():
        candidate = f"unit{candidate}"
    if candidate in _DART_KEYWORDS:
        candidate = f"{candidate}Unit"
    return candidate


async def codegen_dart(config: WorkspaceConfig) -> list[Path]:
    out_file = EVE_DOGMA_UNIT_OUT_PATH
    datasource = GeneratorDatasource(config)
    try:
        dogma_units = await datasource.resources.fsd.get("dogmaUnits")
    finally:
        await datasource.aclose()

    entries = []
    used_names: dict[str, int] = {}
    for unit_id, dogma_unit_def in sorted(dogma_units.items()):
        unit_name = str(dogma_unit_def.get("name", f"Unit {unit_id}"))
        enum_name = _enum_name(unit_name, unit_id)
        if enum_name in used_names:
            prior_unit_id = used_names[enum_name]
            raise ValueError(
                f"Duplicate dogma unit enum name '{enum_name}' for {prior_unit_id} and {unit_id}"
            )
        used_names[enum_name] = unit_id
        entries.append((unit_id, enum_name, unit_name))

    out_file.parent.mkdir(exist_ok=True, parents=True)
    with out_file.open("w", encoding="utf-8") as f:
        f.write(
            "// Automatically generated by `lib.codegen.dogma_unit_id.codegen_dart`\n"
            "// DO NOT EDIT\n\n"
            'part of "eve.dart";\n\n'
        )
        f.write("enum EveDogmaUnitId {\n")
        for index, (unit_id, enum_name, unit_name) in enumerate(entries):
            separator = ";" if index == len(entries) - 1 else ","
            f.write(f"  /// - ID: {unit_id}\n")
            f.write(f"  /// - Name: {unit_name}\n")
            f.write(f"  {enum_name}({unit_id}){separator}\n\n")
        f.write("  const EveDogmaUnitId(this.id);\n\n")
        f.write("  final int id;\n\n")
        f.write("  static const Map<int, EveDogmaUnitId> byId = <int, EveDogmaUnitId>{\n")
        for unit_id, enum_name, _unit_name in entries:
            f.write(f"    {unit_id}: EveDogmaUnitId.{enum_name},\n")
        f.write("  };\n\n")
        f.write("  static EveDogmaUnitId? fromId(int id) => byId[id];\n")
        f.write("}\n")

    return [out_file]
