"""
This module generates dart code for localization support.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import data.lib.config

from data.lib.constant import DART_ROOT


if TYPE_CHECKING:
    from pathlib import Path


def codegen_dart() -> list[Path]:
    trans_map = data.lib.config.CONFIGURATION.localizations.translation
    out_file = DART_ROOT / "config" / "locale.dart"

    out_file.parent.mkdir(exist_ok=True, parents=True)
    with open(out_file, "w+", encoding="utf-8") as f:
        f.write(
            "// Automatically generated by `lib.codegen.localization.codegen_dart`\n"
            "// DO NOT EDIT\n\n"
            "import 'package:freezed_annotation/freezed_annotation.dart';\n\n"
        )
        f.write("part 'locale.g.dart';\n\n")
        f.write("@JsonEnum(alwaysCreate: true)\n")
        f.write("enum Locale {\n")

        for key in trans_map.keys():
            f.write(f"  @JsonValue('{key}')\n")
            f.write(f"  {key},\n")
        f.write("  ;\n")

        f.write("  String get display => switch(this) {\n")
        for key, value in trans_map.items():
            f.write(f"    Locale.{key} => '{value}',\n")
        f.write("  };\n")

        f.write("  String get name => switch(this) {\n")
        for key in trans_map.keys():
            f.write(f"    Locale.{key} => '{key}',\n")
        f.write("  };\n")

        f.write("}\n")

    return [out_file]
