# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: attribute.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'attribute.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import i18n_pb2 as i18n__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61ttribute.proto\x12\tattribute\x1a\ni18n.proto\"\xd5\x02\n\nAttributes\x12\x33\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\".attribute.Attributes.EntriesEntry\x1a\xc0\x01\n\tAttribute\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x14\n\x0c\x64\x65\x66\x61ultValue\x18\x02 \x01(\x01\x12\x12\n\ncategoryID\x18\x03 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x1f\n\x0b\x64isplayName\x18\x05 \x01(\x0b\x32\n.i18n.I18N\x12\x12\n\nhighIsGood\x18\x06 \x02(\x08\x12\x0e\n\x06iconID\x18\x07 \x01(\x05\x12\x11\n\tpublished\x18\x08 \x02(\x08\x12\x0e\n\x06unitID\x18\t \x01(\x05\x1aO\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12.\n\x05value\x18\x02 \x01(\x0b\x32\x1f.attribute.Attributes.Attribute:\x02\x38\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'attribute_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ATTRIBUTES_ENTRIESENTRY']._loaded_options = None
  _globals['_ATTRIBUTES_ENTRIESENTRY']._serialized_options = b'8\001'
  _globals['_ATTRIBUTES']._serialized_start=43
  _globals['_ATTRIBUTES']._serialized_end=384
  _globals['_ATTRIBUTES_ATTRIBUTE']._serialized_start=111
  _globals['_ATTRIBUTES_ATTRIBUTE']._serialized_end=303
  _globals['_ATTRIBUTES_ENTRIESENTRY']._serialized_start=305
  _globals['_ATTRIBUTES_ENTRIESENTRY']._serialized_end=384
# @@protoc_insertion_point(module_scope)
