# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: damage_profile.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64\x61mage_profile.proto\x12\x0e\x64\x61mage_profile\"\x97\x02\n\x0e\x44\x61mageProfiles\x12\x41\n\x06groups\x18\x01 \x03(\x0b\x32\x31.damage_profile.DamageProfiles.DamageProfileGroup\x1a^\n\rDamageProfile\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\n\n\x02\x65m\x18\x02 \x02(\x01\x12\x11\n\texplosive\x18\x03 \x02(\x01\x12\x0f\n\x07kinetic\x18\x04 \x02(\x01\x12\x0f\n\x07thermal\x18\x05 \x02(\x01\x1a\x62\n\x12\x44\x61mageProfileGroup\x12\x0c\n\x04name\x18\x01 \x02(\t\x12>\n\x08profiles\x18\x02 \x03(\x0b\x32,.damage_profile.DamageProfiles.DamageProfile')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'damage_profile_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DAMAGEPROFILES._serialized_start=41
  _DAMAGEPROFILES._serialized_end=320
  _DAMAGEPROFILES_DAMAGEPROFILE._serialized_start=126
  _DAMAGEPROFILES_DAMAGEPROFILE._serialized_end=220
  _DAMAGEPROFILES_DAMAGEPROFILEGROUP._serialized_start=222
  _DAMAGEPROFILES_DAMAGEPROFILEGROUP._serialized_end=320
# @@protoc_insertion_point(module_scope)
