# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fighter.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'fighter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfighter.proto\x12\x07\x66ighter\"\x91\x02\n\x08\x46ighters\x12/\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1e.fighter.Fighters.EntriesEntry\x1aW\n\x07\x46ighter\x12+\n\x04type\x18\x01 \x02(\x0e\x32\x1d.fighter.Fighters.FighterType\x12\x0e\n\x06\x61mount\x18\x02 \x02(\x05\x12\x0f\n\x07\x61\x62ility\x18\x03 \x02(\x05\x1aI\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.fighter.Fighters.Fighter:\x02\x38\x01\"0\n\x0b\x46ighterType\x12\t\n\x05LIGHT\x10\x01\x12\x0b\n\x07SUPPORT\x10\x02\x12\t\n\x05HEAVY\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fighter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FIGHTERS_ENTRIESENTRY']._loaded_options = None
  _globals['_FIGHTERS_ENTRIESENTRY']._serialized_options = b'8\001'
  _globals['_FIGHTERS']._serialized_start=27
  _globals['_FIGHTERS']._serialized_end=300
  _globals['_FIGHTERS_FIGHTER']._serialized_start=88
  _globals['_FIGHTERS_FIGHTER']._serialized_end=175
  _globals['_FIGHTERS_ENTRIESENTRY']._serialized_start=177
  _globals['_FIGHTERS_ENTRIESENTRY']._serialized_end=250
  _globals['_FIGHTERS_FIGHTERTYPE']._serialized_start=252
  _globals['_FIGHTERS_FIGHTERTYPE']._serialized_end=300
# @@protoc_insertion_point(module_scope)
