# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: groups.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import i18n_pb2 as i18n__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgroups.proto\x12\x06groups\x1a\ni18n.proto\"\xf2\x01\n\x06Groups\x12,\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1b.groups.Groups.EntriesEntry\x1at\n\x05Group\x12\x18\n\x04name\x18\x01 \x02(\x0b\x32\n.i18n.I18N\x12\x12\n\ncategoryID\x18\x02 \x02(\x05\x12\x11\n\tpublished\x18\x03 \x02(\x08\x12\r\n\x05types\x18\x04 \x03(\x05\x12\x1b\n\x13relatedMarketGroups\x18\x05 \x03(\x05\x1a\x44\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.groups.Groups.Group:\x02\x38\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'groups_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GROUPS_ENTRIESENTRY._options = None
  _GROUPS_ENTRIESENTRY._serialized_options = b'8\001'
  _GROUPS._serialized_start=37
  _GROUPS._serialized_end=279
  _GROUPS_GROUP._serialized_start=93
  _GROUPS_GROUP._serialized_end=209
  _GROUPS_ENTRIESENTRY._serialized_start=211
  _GROUPS_ENTRIESENTRY._serialized_end=279
# @@protoc_insertion_point(module_scope)
