# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: groups.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'groups.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import i18n_pb2 as i18n__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgroups.proto\x12\x06groups\x1a\ni18n.proto\"\xcb\x01\n\x06Groups\x12,\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1b.groups.Groups.EntriesEntry\x1aM\n\x05Group\x12\x18\n\x04name\x18\x01 \x02(\x0b\x32\n.i18n.I18N\x12\r\n\x05types\x18\x02 \x03(\x05\x12\x1b\n\x13relatedMarketGroups\x18\x03 \x03(\x05\x1a\x44\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.groups.Groups.Group:\x02\x38\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'groups_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GROUPS_ENTRIESENTRY']._loaded_options = None
  _globals['_GROUPS_ENTRIESENTRY']._serialized_options = b'8\001'
  _globals['_GROUPS']._serialized_start=37
  _globals['_GROUPS']._serialized_end=240
  _globals['_GROUPS_GROUP']._serialized_start=93
  _globals['_GROUPS_GROUP']._serialized_end=170
  _globals['_GROUPS_ENTRIESENTRY']._serialized_start=172
  _globals['_GROUPS_ENTRIESENTRY']._serialized_end=240
# @@protoc_insertion_point(module_scope)
