# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: market_group.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'market_group.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import i18n_pb2 as i18n__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12market_group.proto\x12\x0cmarket_group\x1a\ni18n.proto\"\x92\x02\n\x0cMarketGroups\x12\x38\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\'.market_group.MarketGroups.EntriesEntry\x1ap\n\x0bMarketGroup\x12\x18\n\x04name\x18\x01 \x02(\x0b\x32\n.i18n.I18N\x12\x13\n\x0bparentGroup\x18\x02 \x01(\x05\x12\x0e\n\x06iconID\x18\x03 \x01(\x05\x12\r\n\x05types\x18\x04 \x03(\x05\x12\x13\n\x0b\x63hildGroups\x18\x05 \x03(\x05\x1aV\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x35\n\x05value\x18\x02 \x01(\x0b\x32&.market_group.MarketGroups.MarketGroup:\x02\x38\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'market_group_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MARKETGROUPS_ENTRIESENTRY']._loaded_options = None
  _globals['_MARKETGROUPS_ENTRIESENTRY']._serialized_options = b'8\001'
  _globals['_MARKETGROUPS']._serialized_start=49
  _globals['_MARKETGROUPS']._serialized_end=323
  _globals['_MARKETGROUPS_MARKETGROUP']._serialized_start=123
  _globals['_MARKETGROUPS_MARKETGROUP']._serialized_end=235
  _globals['_MARKETGROUPS_ENTRIESENTRY']._serialized_start=237
  _globals['_MARKETGROUPS_ENTRIESENTRY']._serialized_end=323
# @@protoc_insertion_point(module_scope)
