# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: subsystem.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import i18n_pb2 as i18n__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsubsystem.proto\x12\tsubsystem\x1a\ni18n.proto\"\xca\x04\n\rShipSubsystem\x12\x32\n\x05ships\x18\x01 \x03(\x0b\x32#.subsystem.ShipSubsystem.ShipsEntry\x12<\n\nsubsystems\x18\x02 \x03(\x0b\x32(.subsystem.ShipSubsystem.SubsystemsEntry\x1a\xae\x01\n\x04Ship\x12\x11\n\toffensive\x18\x01 \x03(\x05\x12\x17\n\x0foffensiveMarket\x18\x02 \x02(\x05\x12\x12\n\npropulsion\x18\x03 \x03(\x05\x12\x18\n\x10propulsionMarket\x18\x04 \x02(\x05\x12\x0c\n\x04\x63ore\x18\x05 \x03(\x05\x12\x12\n\ncoreMarket\x18\x06 \x02(\x05\x12\x11\n\tdefensive\x18\x07 \x03(\x05\x12\x17\n\x0f\x64\x65\x66\x65nsiveMarket\x18\x08 \x02(\x05\x1ar\n\tSubsystem\x12\x18\n\x04name\x18\x01 \x02(\x0b\x32\n.i18n.I18N\x12\x0c\n\x04high\x18\x02 \x01(\x05\x12\x0e\n\x06medium\x18\x03 \x01(\x05\x12\x0b\n\x03low\x18\x04 \x01(\x05\x12\x0e\n\x06turret\x18\x05 \x01(\x05\x12\x10\n\x08launcher\x18\x06 \x01(\x05\x1aK\n\nShipsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.subsystem.ShipSubsystem.Ship:\x02\x38\x01\x1aU\n\x0fSubsystemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x31\n\x05value\x18\x02 \x01(\x0b\x32\".subsystem.ShipSubsystem.Subsystem:\x02\x38\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'subsystem_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SHIPSUBSYSTEM_SHIPSENTRY._options = None
  _SHIPSUBSYSTEM_SHIPSENTRY._serialized_options = b'8\001'
  _SHIPSUBSYSTEM_SUBSYSTEMSENTRY._options = None
  _SHIPSUBSYSTEM_SUBSYSTEMSENTRY._serialized_options = b'8\001'
  _SHIPSUBSYSTEM._serialized_start=43
  _SHIPSUBSYSTEM._serialized_end=629
  _SHIPSUBSYSTEM_SHIP._serialized_start=175
  _SHIPSUBSYSTEM_SHIP._serialized_end=349
  _SHIPSUBSYSTEM_SUBSYSTEM._serialized_start=351
  _SHIPSUBSYSTEM_SUBSYSTEM._serialized_end=465
  _SHIPSUBSYSTEM_SHIPSENTRY._serialized_start=467
  _SHIPSUBSYSTEM_SHIPSENTRY._serialized_end=542
  _SHIPSUBSYSTEM_SUBSYSTEMSENTRY._serialized_start=544
  _SHIPSUBSYSTEM_SUBSYSTEMSENTRY._serialized_end=629
# @@protoc_insertion_point(module_scope)
