# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: unit.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'unit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nunit.proto\x12\x04unit\"\xb4\x01\n\x05Units\x12)\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x18.unit.Units.EntriesEntry\x1a>\n\x04Unit\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x13\n\x0b\x64isplayName\x18\x02 \x02(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x02(\t\x1a@\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.unit.Units.Unit:\x02\x38\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UNITS_ENTRIESENTRY']._loaded_options = None
  _globals['_UNITS_ENTRIESENTRY']._serialized_options = b'8\001'
  _globals['_UNITS']._serialized_start=21
  _globals['_UNITS']._serialized_end=201
  _globals['_UNITS_UNIT']._serialized_start=73
  _globals['_UNITS_UNIT']._serialized_end=135
  _globals['_UNITS_ENTRIESENTRY']._serialized_start=137
  _globals['_UNITS_ENTRIESENTRY']._serialized_end=201
# @@protoc_insertion_point(module_scope)
