[package]
name = "rust_lib_eve_fit_assistant"
version = "0.10.0"
edition = "2021" # not 2024 because of flutter_rust_bridge

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.13.0-beta.6"
efa-chat = { path = "lib/efa-chat" }
eve-fit-os = { path = "../../../packages/eve-fit-os" }
anyhow = "1.0.100"
futures = "0.3"
log = "0.4"

[target.'cfg(target_os = "android")'.dependencies]
rustls-platform-verifier = "0.7"
jni = "0.22"
ndk-context = "0.1"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
