// GENERATED — see packages/eve-fit-os/data/patches/system_effects.yaml for the
// hand-authored buff definitions and the generation tooling under
// packages/eve-fit-os/tool/system_effects/. Regenerate instead of hand-editing.
//
// The catalog carries no buff values: presets describe how to resolve values
// from the active snapshot's effect-beacon dogma at runtime; see
// system_effect_resolver.dart (hand-written) for the expansion logic.

import "package:eve_fit_assistant/storage/fit/schema.dart";

/// Category of a system effect preset, driving the picker grouping.
enum SystemEffectCategory {
  wormhole("虫洞", "Wormhole"),
  abyssalWeather("深渊天气", "Abyssal Weather"),
  storm("风暴", "Storm"),
  sovUpgrade("主权升级", "Sovereignty Upgrade"),
  triglavian("三神裔", "Triglavian"),
  insurgency("海盗叛乱", "Pirate Insurgency"),
  abyssalHazard("深渊危害", "Abyssal Hazard");

  const SystemEffectCategory(this.zh, this.en);

  final String zh;
  final String en;
}

/// A system-wide environment preset: bilingual display metadata plus a
/// rule for expanding the preset into concrete [FitSystemBuff] entries
/// from the active snapshot's effect-beacon dogma.
class SystemEffectPreset {
  const SystemEffectPreset({
    required this.id,
    required this.category,
    required this.zh,
    required this.en,
    this.beaconTypeId,
    this.buffAttrs,
    this.warfareFromBeacon = false,
    this.staticBuffs,
  });

  final String id;
  final SystemEffectCategory category;
  final String zh;
  final String en;

  /// Effect beacon type carrying this preset's values in the active
  /// snapshot's engine data; null for [staticBuffs] presets.
  final int? beaconTypeId;

  /// Buff ID -> beacon attribute ID: each buff's value is the beacon's
  /// attribute value (wormholes and metaliminal/volatile storms).
  final Map<int, int>? buffAttrs;

  /// Expand the beacon's `warfareBuff1-4ID/Value` attribute pairs
  /// directly (abyssal weather and hazard clouds).
  final bool warfareFromBeacon;

  /// Pre-expanded entries for effects whose beacons carry no usable
  /// dogma on any server (sovereignty upgrades, Triglavian space,
  /// insurgency suppression); accepted-risk hardcodes.
  final List<FitSystemBuff>? staticBuffs;
}

/// All environment presets, in picker display order.
const systemEffectCatalog = <SystemEffectPreset>[
  SystemEffectPreset(
    id: "wormhole.black_hole.1",
    category: SystemEffectCategory.wormhole,
    zh: "黑洞 — 一类",
    en: "Black Hole — Class 1",
    beaconTypeId: 30845,
    buffAttrs: {-2006: 169, -2007: 237, -2008: 1469, -2009: 1470, -2010: 1483, -2011: 1969},
  ),
  SystemEffectPreset(
    id: "wormhole.black_hole.2",
    category: SystemEffectCategory.wormhole,
    zh: "黑洞 — 二类",
    en: "Black Hole — Class 2",
    beaconTypeId: 30850,
    buffAttrs: {-2006: 169, -2007: 237, -2008: 1469, -2009: 1470, -2010: 1483, -2011: 1969},
  ),
  SystemEffectPreset(
    id: "wormhole.black_hole.3",
    category: SystemEffectCategory.wormhole,
    zh: "黑洞 — 三类",
    en: "Black Hole — Class 3",
    beaconTypeId: 30851,
    buffAttrs: {-2006: 169, -2007: 237, -2008: 1469, -2009: 1470, -2010: 1483, -2011: 1969},
  ),
  SystemEffectPreset(
    id: "wormhole.black_hole.4",
    category: SystemEffectCategory.wormhole,
    zh: "黑洞 — 四类",
    en: "Black Hole — Class 4",
    beaconTypeId: 30852,
    buffAttrs: {-2006: 169, -2007: 237, -2008: 1469, -2009: 1470, -2010: 1483, -2011: 1969},
  ),
  SystemEffectPreset(
    id: "wormhole.black_hole.5",
    category: SystemEffectCategory.wormhole,
    zh: "黑洞 — 五类",
    en: "Black Hole — Class 5",
    beaconTypeId: 30853,
    buffAttrs: {-2006: 169, -2007: 237, -2008: 1469, -2009: 1470, -2010: 1483, -2011: 1969},
  ),
  SystemEffectPreset(
    id: "wormhole.black_hole.6",
    category: SystemEffectCategory.wormhole,
    zh: "黑洞 — 六类",
    en: "Black Hole — Class 6",
    beaconTypeId: 30854,
    buffAttrs: {-2006: 169, -2007: 237, -2008: 1469, -2009: 1470, -2010: 1483, -2011: 1969},
  ),
  SystemEffectPreset(
    id: "wormhole.cataclysmic_variable.1",
    category: SystemEffectCategory.wormhole,
    zh: "激变变星 — 一类",
    en: "Cataclysmic Variable — Class 1",
    beaconTypeId: 30846,
    buffAttrs: {
      -2012: 1495,
      -2013: 1496,
      -2014: 1497,
      -2015: 1498,
      -2016: 1499,
      -2017: 1500,
      -2018: 1840,
    },
  ),
  SystemEffectPreset(
    id: "wormhole.cataclysmic_variable.2",
    category: SystemEffectCategory.wormhole,
    zh: "激变变星 — 二类",
    en: "Cataclysmic Variable — Class 2",
    beaconTypeId: 30880,
    buffAttrs: {
      -2012: 1495,
      -2013: 1496,
      -2014: 1497,
      -2015: 1498,
      -2016: 1499,
      -2017: 1500,
      -2018: 1840,
    },
  ),
  SystemEffectPreset(
    id: "wormhole.cataclysmic_variable.3",
    category: SystemEffectCategory.wormhole,
    zh: "激变变星 — 三类",
    en: "Cataclysmic Variable — Class 3",
    beaconTypeId: 30881,
    buffAttrs: {
      -2012: 1495,
      -2013: 1496,
      -2014: 1497,
      -2015: 1498,
      -2016: 1499,
      -2017: 1500,
      -2018: 1840,
    },
  ),
  SystemEffectPreset(
    id: "wormhole.cataclysmic_variable.4",
    category: SystemEffectCategory.wormhole,
    zh: "激变变星 — 四类",
    en: "Cataclysmic Variable — Class 4",
    beaconTypeId: 30884,
    buffAttrs: {
      -2012: 1495,
      -2013: 1496,
      -2014: 1497,
      -2015: 1498,
      -2016: 1499,
      -2017: 1500,
      -2018: 1840,
    },
  ),
  SystemEffectPreset(
    id: "wormhole.cataclysmic_variable.5",
    category: SystemEffectCategory.wormhole,
    zh: "激变变星 — 五类",
    en: "Cataclysmic Variable — Class 5",
    beaconTypeId: 30883,
    buffAttrs: {
      -2012: 1495,
      -2013: 1496,
      -2014: 1497,
      -2015: 1498,
      -2016: 1499,
      -2017: 1500,
      -2018: 1840,
    },
  ),
  SystemEffectPreset(
    id: "wormhole.cataclysmic_variable.6",
    category: SystemEffectCategory.wormhole,
    zh: "激变变星 — 六类",
    en: "Cataclysmic Variable — Class 6",
    beaconTypeId: 30882,
    buffAttrs: {
      -2012: 1495,
      -2013: 1496,
      -2014: 1497,
      -2015: 1498,
      -2016: 1499,
      -2017: 1500,
      -2018: 1840,
    },
  ),
  SystemEffectPreset(
    id: "wormhole.magnetar.1",
    category: SystemEffectCategory.wormhole,
    zh: "磁星 — 一类",
    en: "Magnetar — Class 1",
    beaconTypeId: 30847,
    buffAttrs: {-2019: 237, -2020: 244, -2021: 1482, -2022: 1967, -2023: 1968},
  ),
  SystemEffectPreset(
    id: "wormhole.magnetar.2",
    category: SystemEffectCategory.wormhole,
    zh: "磁星 — 二类",
    en: "Magnetar — Class 2",
    beaconTypeId: 30860,
    buffAttrs: {-2019: 237, -2020: 244, -2021: 1482, -2022: 1967, -2023: 1968},
  ),
  SystemEffectPreset(
    id: "wormhole.magnetar.3",
    category: SystemEffectCategory.wormhole,
    zh: "磁星 — 三类",
    en: "Magnetar — Class 3",
    beaconTypeId: 30861,
    buffAttrs: {-2019: 237, -2020: 244, -2021: 1482, -2022: 1967, -2023: 1968},
  ),
  SystemEffectPreset(
    id: "wormhole.magnetar.4",
    category: SystemEffectCategory.wormhole,
    zh: "磁星 — 四类",
    en: "Magnetar — Class 4",
    beaconTypeId: 30862,
    buffAttrs: {-2019: 237, -2020: 244, -2021: 1482, -2022: 1967, -2023: 1968},
  ),
  SystemEffectPreset(
    id: "wormhole.magnetar.5",
    category: SystemEffectCategory.wormhole,
    zh: "磁星 — 五类",
    en: "Magnetar — Class 5",
    beaconTypeId: 30863,
    buffAttrs: {-2019: 237, -2020: 244, -2021: 1482, -2022: 1967, -2023: 1968},
  ),
  SystemEffectPreset(
    id: "wormhole.magnetar.6",
    category: SystemEffectCategory.wormhole,
    zh: "磁星 — 六类",
    en: "Magnetar — Class 6",
    beaconTypeId: 30864,
    buffAttrs: {-2019: 237, -2020: 244, -2021: 1482, -2022: 1967, -2023: 1968},
  ),
  SystemEffectPreset(
    id: "wormhole.pulsar.1",
    category: SystemEffectCategory.wormhole,
    zh: "脉冲星 — 一类",
    en: "Pulsar — Class 1",
    beaconTypeId: 30844,
    buffAttrs: {-2001: 146, -2002: 652, -2003: 1465, -2004: 1500, -2005: 1966},
  ),
  SystemEffectPreset(
    id: "wormhole.pulsar.2",
    category: SystemEffectCategory.wormhole,
    zh: "脉冲星 — 二类",
    en: "Pulsar — Class 2",
    beaconTypeId: 30865,
    buffAttrs: {-2001: 146, -2002: 652, -2003: 1465, -2004: 1500, -2005: 1966},
  ),
  SystemEffectPreset(
    id: "wormhole.pulsar.3",
    category: SystemEffectCategory.wormhole,
    zh: "脉冲星 — 三类",
    en: "Pulsar — Class 3",
    beaconTypeId: 30866,
    buffAttrs: {-2001: 146, -2002: 652, -2003: 1465, -2004: 1500, -2005: 1966},
  ),
  SystemEffectPreset(
    id: "wormhole.pulsar.4",
    category: SystemEffectCategory.wormhole,
    zh: "脉冲星 — 四类",
    en: "Pulsar — Class 4",
    beaconTypeId: 30867,
    buffAttrs: {-2001: 146, -2002: 652, -2003: 1465, -2004: 1500, -2005: 1966},
  ),
  SystemEffectPreset(
    id: "wormhole.pulsar.5",
    category: SystemEffectCategory.wormhole,
    zh: "脉冲星 — 五类",
    en: "Pulsar — Class 5",
    beaconTypeId: 30868,
    buffAttrs: {-2001: 146, -2002: 652, -2003: 1465, -2004: 1500, -2005: 1966},
  ),
  SystemEffectPreset(
    id: "wormhole.pulsar.6",
    category: SystemEffectCategory.wormhole,
    zh: "脉冲星 — 六类",
    en: "Pulsar — Class 6",
    beaconTypeId: 30869,
    buffAttrs: {-2001: 146, -2002: 652, -2003: 1465, -2004: 1500, -2005: 1966},
  ),
  SystemEffectPreset(
    id: "wormhole.red_giant.1",
    category: SystemEffectCategory.wormhole,
    zh: "红巨星 — 一类",
    en: "Red Giant — Class 1",
    beaconTypeId: 30848,
    buffAttrs: {-2024: 1485, -2025: 1486, -2026: 1487, -2027: 1488, -2028: 1488},
  ),
  SystemEffectPreset(
    id: "wormhole.red_giant.2",
    category: SystemEffectCategory.wormhole,
    zh: "红巨星 — 二类",
    en: "Red Giant — Class 2",
    beaconTypeId: 30870,
    buffAttrs: {-2024: 1485, -2025: 1486, -2026: 1487, -2027: 1488, -2028: 1488},
  ),
  SystemEffectPreset(
    id: "wormhole.red_giant.3",
    category: SystemEffectCategory.wormhole,
    zh: "红巨星 — 三类",
    en: "Red Giant — Class 3",
    beaconTypeId: 30871,
    buffAttrs: {-2024: 1485, -2025: 1486, -2026: 1487, -2027: 1488, -2028: 1488},
  ),
  SystemEffectPreset(
    id: "wormhole.red_giant.4",
    category: SystemEffectCategory.wormhole,
    zh: "红巨星 — 四类",
    en: "Red Giant — Class 4",
    beaconTypeId: 30872,
    buffAttrs: {-2024: 1485, -2025: 1486, -2026: 1487, -2027: 1488, -2028: 1488},
  ),
  SystemEffectPreset(
    id: "wormhole.red_giant.5",
    category: SystemEffectCategory.wormhole,
    zh: "红巨星 — 五类",
    en: "Red Giant — Class 5",
    beaconTypeId: 30873,
    buffAttrs: {-2024: 1485, -2025: 1486, -2026: 1487, -2027: 1488, -2028: 1488},
  ),
  SystemEffectPreset(
    id: "wormhole.red_giant.6",
    category: SystemEffectCategory.wormhole,
    zh: "红巨星 — 六类",
    en: "Red Giant — Class 6",
    beaconTypeId: 30874,
    buffAttrs: {-2024: 1485, -2025: 1486, -2026: 1487, -2027: 1488, -2028: 1488},
  ),
  SystemEffectPreset(
    id: "wormhole.wolf_rayet.1",
    category: SystemEffectCategory.wormhole,
    zh: "沃尔夫-拉叶星 — 一类",
    en: "Wolf Rayet — Class 1",
    beaconTypeId: 30849,
    buffAttrs: {-2029: 148, -2030: 652, -2031: 1489, -2032: 1493},
  ),
  SystemEffectPreset(
    id: "wormhole.wolf_rayet.2",
    category: SystemEffectCategory.wormhole,
    zh: "沃尔夫-拉叶星 — 二类",
    en: "Wolf Rayet — Class 2",
    beaconTypeId: 30875,
    buffAttrs: {-2029: 148, -2030: 652, -2031: 1489, -2032: 1493},
  ),
  SystemEffectPreset(
    id: "wormhole.wolf_rayet.3",
    category: SystemEffectCategory.wormhole,
    zh: "沃尔夫-拉叶星 — 三类",
    en: "Wolf Rayet — Class 3",
    beaconTypeId: 30876,
    buffAttrs: {-2029: 148, -2030: 652, -2031: 1489, -2032: 1493},
  ),
  SystemEffectPreset(
    id: "wormhole.wolf_rayet.4",
    category: SystemEffectCategory.wormhole,
    zh: "沃尔夫-拉叶星 — 四类",
    en: "Wolf Rayet — Class 4",
    beaconTypeId: 30877,
    buffAttrs: {-2029: 148, -2030: 652, -2031: 1489, -2032: 1493},
  ),
  SystemEffectPreset(
    id: "wormhole.wolf_rayet.5",
    category: SystemEffectCategory.wormhole,
    zh: "沃尔夫-拉叶星 — 五类",
    en: "Wolf Rayet — Class 5",
    beaconTypeId: 30878,
    buffAttrs: {-2029: 148, -2030: 652, -2031: 1489, -2032: 1493},
  ),
  SystemEffectPreset(
    id: "wormhole.wolf_rayet.6",
    category: SystemEffectCategory.wormhole,
    zh: "沃尔夫-拉叶星 — 六类",
    en: "Wolf Rayet — Class 6",
    beaconTypeId: 30879,
    buffAttrs: {-2029: 148, -2030: 652, -2031: 1489, -2032: 1493},
  ),
  SystemEffectPreset(
    id: "weather.electrical.1",
    category: SystemEffectCategory.abyssalWeather,
    zh: "电子风暴 — 1 级",
    en: "Electrical Storm — Tier 1",
    beaconTypeId: 47381,
    warfareFromBeacon: true,
  ),
  SystemEffectPreset(
    id: "weather.electrical.2",
    category: SystemEffectCategory.abyssalWeather,
    zh: "电子风暴 — 2 级",
    en: "Electrical Storm — Tier 2",
    beaconTypeId: 47382,
    warfareFromBeacon: true,
  ),
  SystemEffectPreset(
    id: "weather.electrical.3",
    category: SystemEffectCategory.abyssalWeather,
    zh: "电子风暴 — 3 级",
    en: "Electrical Storm — Tier 3",
    beaconTypeId: 47383,
    warfareFromBeacon: true,
  ),
  SystemEffectPreset(
    id: "weather.exotic.1",
    category: SystemEffectCategory.abyssalWeather,
    zh: "异种粒子风暴 — 1 级",
    en: "Exotic Particle Storm — Tier 1",
    beaconTypeId: 47387,
    warfareFromBeacon: true,
  ),
  SystemEffectPreset(
    id: "weather.exotic.2",
    category: SystemEffectCategory.abyssalWeather,
    zh: "异种粒子风暴 — 2 级",
    en: "Exotic Particle Storm — Tier 2",
    beaconTypeId: 47388,
    warfareFromBeacon: true,
  ),
  SystemEffectPreset(
    id: "weather.exotic.3",
    category: SystemEffectCategory.abyssalWeather,
    zh: "异种粒子风暴 — 3 级",
    en: "Exotic Particle Storm — Tier 3",
    beaconTypeId: 47389,
    warfareFromBeacon: true,
  ),
  SystemEffectPreset(
    id: "weather.infernal.1",
    category: SystemEffectCategory.abyssalWeather,
    zh: "等离子火焰风暴 — 1 级",
    en: "Plasma Firestorm — Tier 1",
    beaconTypeId: 47390,
    warfareFromBeacon: true,
  ),
  SystemEffectPreset(
    id: "weather.infernal.2",
    category: SystemEffectCategory.abyssalWeather,
    zh: "等离子火焰风暴 — 2 级",
    en: "Plasma Firestorm — Tier 2",
    beaconTypeId: 47391,
    warfareFromBeacon: true,
  ),
  SystemEffectPreset(
    id: "weather.infernal.3",
    category: SystemEffectCategory.abyssalWeather,
    zh: "等离子火焰风暴 — 3 级",
    en: "Plasma Firestorm — Tier 3",
    beaconTypeId: 47392,
    warfareFromBeacon: true,
  ),
  SystemEffectPreset(
    id: "weather.darkness.1",
    category: SystemEffectCategory.abyssalWeather,
    zh: "暗物质场 — 1 级",
    en: "Dark Matter Field — Tier 1",
    beaconTypeId: 47378,
    warfareFromBeacon: true,
  ),
  SystemEffectPreset(
    id: "weather.darkness.2",
    category: SystemEffectCategory.abyssalWeather,
    zh: "暗物质场 — 2 级",
    en: "Dark Matter Field — Tier 2",
    beaconTypeId: 47379,
    warfareFromBeacon: true,
  ),
  SystemEffectPreset(
    id: "weather.darkness.3",
    category: SystemEffectCategory.abyssalWeather,
    zh: "暗物质场 — 3 级",
    en: "Dark Matter Field — Tier 3",
    beaconTypeId: 47380,
    warfareFromBeacon: true,
  ),
  SystemEffectPreset(
    id: "weather.caustic.1",
    category: SystemEffectCategory.abyssalWeather,
    zh: "伽玛射线余波 — 1 级",
    en: "Gamma-Ray Afterglow — Tier 1",
    beaconTypeId: 47384,
    warfareFromBeacon: true,
  ),
  SystemEffectPreset(
    id: "weather.caustic.2",
    category: SystemEffectCategory.abyssalWeather,
    zh: "伽玛射线余波 — 2 级",
    en: "Gamma-Ray Afterglow — Tier 2",
    beaconTypeId: 47385,
    warfareFromBeacon: true,
  ),
  SystemEffectPreset(
    id: "weather.caustic.3",
    category: SystemEffectCategory.abyssalWeather,
    zh: "伽玛射线余波 — 3 级",
    en: "Gamma-Ray Afterglow — Tier 3",
    beaconTypeId: 47386,
    warfareFromBeacon: true,
  ),
  SystemEffectPreset(
    id: "storm.electrical.strong",
    category: SystemEffectCategory.storm,
    zh: "强超阈限电子风暴",
    en: "Strong Metaliminal Electrical Storm",
    beaconTypeId: 56057,
    buffAttrs: {-2101: 984, -2102: 1500},
  ),
  SystemEffectPreset(
    id: "storm.electrical.weak",
    category: SystemEffectCategory.storm,
    zh: "弱超阈限电子风暴",
    en: "Weak Metaliminal Electrical Storm",
    beaconTypeId: 56064,
    buffAttrs: {-2101: 984, -2102: 1500},
  ),
  SystemEffectPreset(
    id: "storm.exotic.strong",
    category: SystemEffectCategory.storm,
    zh: "强超阈限异种物质风暴",
    en: "Strong Metaliminal Exotic Matter Storm",
    beaconTypeId: 56059,
    buffAttrs: {-2103: 986, -2104: 3098, -2105: 3099, -2106: 203, -2107: 601, -2108: 566},
  ),
  SystemEffectPreset(
    id: "storm.exotic.weak",
    category: SystemEffectCategory.storm,
    zh: "弱超阈限异种物质风暴",
    en: "Weak Metaliminal Exotic Matter Storm",
    beaconTypeId: 56058,
    buffAttrs: {-2103: 986, -2104: 3098, -2105: 3099, -2106: 203, -2107: 601, -2108: 566},
  ),
  SystemEffectPreset(
    id: "storm.gamma.strong",
    category: SystemEffectCategory.storm,
    zh: "强超阈限伽玛射线风暴",
    en: "Strong Metaliminal Gamma Ray Storm",
    beaconTypeId: 56061,
    buffAttrs: {-2109: 985, -2110: 1497, -2111: 1498, -2112: 146, -2113: 1499, -2114: 652},
  ),
  SystemEffectPreset(
    id: "storm.gamma.weak",
    category: SystemEffectCategory.storm,
    zh: "弱超阈限伽玛射线风暴",
    en: "Weak Metaliminal Gamma Ray Storm",
    beaconTypeId: 56060,
    buffAttrs: {-2109: 985, -2110: 1497, -2111: 1498, -2112: 146, -2113: 1499, -2114: 652},
  ),
  SystemEffectPreset(
    id: "storm.plasma.strong",
    category: SystemEffectCategory.storm,
    zh: "强超阈限等离子火焰风暴",
    en: "Strong Metaliminal Plasma Firestorm",
    beaconTypeId: 56063,
    buffAttrs: {-2115: 987, -2116: 1482, -2117: 244, -2118: 1967, -2119: 148},
  ),
  SystemEffectPreset(
    id: "storm.plasma.weak",
    category: SystemEffectCategory.storm,
    zh: "弱超阈限等离子火焰风暴",
    en: "Weak Metaliminal Plasma Firestorm",
    beaconTypeId: 56062,
    buffAttrs: {-2115: 987, -2116: 1482, -2117: 244, -2118: 1967, -2119: 148},
  ),
  SystemEffectPreset(
    id: "storm.icestorm.strong",
    category: SystemEffectCategory.storm,
    zh: "强不稳定冰风暴",
    en: "Strong Volatile Ice Storm",
    beaconTypeId: 56967,
    buffAttrs: {-2120: 987, -2121: 1229},
  ),
  SystemEffectPreset(
    id: "storm.icestorm.weak",
    category: SystemEffectCategory.storm,
    zh: "弱不稳定冰风暴",
    en: "Weak Volatile Ice Storm",
    beaconTypeId: 56997,
    buffAttrs: {-2120: 987, -2121: 1229},
  ),
  SystemEffectPreset(
    id: "sov.gamma",
    category: SystemEffectCategory.sovUpgrade,
    zh: "伽玛主权升级",
    en: "Gamma Sovereignty Upgrade",
    staticBuffs: [
      FitSystemBuff(buffId: 2433, value: 5, presetId: "sov.gamma"),
      FitSystemBuff(buffId: 2434, value: 10, presetId: "sov.gamma"),
      FitSystemBuff(buffId: 2441, value: 5, presetId: "sov.gamma"),
    ],
  ),
  SystemEffectPreset(
    id: "sov.plasma",
    category: SystemEffectCategory.sovUpgrade,
    zh: "等离子主权升级",
    en: "Plasma Sovereignty Upgrade",
    staticBuffs: [
      FitSystemBuff(buffId: 2442, value: 5, presetId: "sov.plasma"),
      FitSystemBuff(buffId: 2435, value: 5, presetId: "sov.plasma"),
      FitSystemBuff(buffId: 2436, value: 10, presetId: "sov.plasma"),
    ],
  ),
  SystemEffectPreset(
    id: "sov.electric",
    category: SystemEffectCategory.sovUpgrade,
    zh: "电子主权升级",
    en: "Electric Sovereignty Upgrade",
    staticBuffs: [
      FitSystemBuff(buffId: 2437, value: -25, presetId: "sov.electric"),
      FitSystemBuff(buffId: 2438, value: 25, presetId: "sov.electric"),
    ],
  ),
  SystemEffectPreset(
    id: "sov.exotic",
    category: SystemEffectCategory.sovUpgrade,
    zh: "异种主权升级",
    en: "Exotic Sovereignty Upgrade",
    staticBuffs: [
      FitSystemBuff(buffId: 2440, value: 2, presetId: "sov.exotic"),
      FitSystemBuff(buffId: 2439, value: 25, presetId: "sov.exotic"),
    ],
  ),
  SystemEffectPreset(
    id: "trig.pochven",
    category: SystemEffectCategory.triglavian,
    zh: "波赫文（最终林隙）",
    en: "Pochven (Final Liminality)",
    staticBuffs: [
      FitSystemBuff(buffId: 2534, value: -50, presetId: "trig.pochven"),
      FitSystemBuff(buffId: 2535, value: -30, presetId: "trig.pochven"),
      FitSystemBuff(buffId: 2538, value: 30, presetId: "trig.pochven"),
      FitSystemBuff(buffId: 2539, value: 30, presetId: "trig.pochven"),
    ],
  ),
  SystemEffectPreset(
    id: "trig.minor_victory",
    category: SystemEffectCategory.triglavian,
    zh: "三神裔局部胜利",
    en: "Triglavian Minor Victory",
    staticBuffs: [
      FitSystemBuff(buffId: 2534, value: -50, presetId: "trig.minor_victory"),
      FitSystemBuff(buffId: 2538, value: 15, presetId: "trig.minor_victory"),
      FitSystemBuff(buffId: 2539, value: 15, presetId: "trig.minor_victory"),
    ],
  ),
  SystemEffectPreset(
    id: "insurgency.suppression",
    category: SystemEffectCategory.insurgency,
    zh: "叛乱镇压",
    en: "Insurgency Suppression",
    staticBuffs: [FitSystemBuff(buffId: 2405, value: 10, presetId: "insurgency.suppression")],
  ),
  SystemEffectPreset(
    id: "hazard.bioluminescence",
    category: SystemEffectCategory.abyssalHazard,
    zh: "生物荧光云",
    en: "Bioluminescence Cloud",
    beaconTypeId: 47439,
    warfareFromBeacon: true,
  ),
  SystemEffectPreset(
    id: "hazard.caustic",
    category: SystemEffectCategory.abyssalHazard,
    zh: "腐蚀云",
    en: "Caustic Cloud",
    beaconTypeId: 47436,
    warfareFromBeacon: true,
  ),
  SystemEffectPreset(
    id: "hazard.filament_small",
    category: SystemEffectCategory.abyssalHazard,
    zh: "纤维云（小）",
    en: "Filament Cloud (Small)",
    beaconTypeId: 47620,
    warfareFromBeacon: true,
  ),
  SystemEffectPreset(
    id: "hazard.filament_medium",
    category: SystemEffectCategory.abyssalHazard,
    zh: "纤维云（中）",
    en: "Filament Cloud (Medium)",
    beaconTypeId: 47472,
    warfareFromBeacon: true,
  ),
  SystemEffectPreset(
    id: "hazard.filament_large",
    category: SystemEffectCategory.abyssalHazard,
    zh: "纤维云（大）",
    en: "Filament Cloud (Large)",
    beaconTypeId: 47473,
    warfareFromBeacon: true,
  ),
];

/// Preset lookup by id.
final systemEffectPresetById = <String, SystemEffectPreset>{
  for (final preset in systemEffectCatalog) preset.id: preset,
};

/// A pickable buff entry of the custom-buff library.
class SystemBuffLibraryEntry {
  const SystemBuffLibraryEntry({
    required this.buffId,
    required this.zh,
    required this.en,
    this.defaultBeaconTypeId,
    this.defaultAttrId,
    this.staticDefault,
  });

  final int buffId;
  final String zh;
  final String en;

  /// Beacon whose dogma provides the pre-filled strength in the
  /// active snapshot (weakest tier/class of the effect); the user can
  /// edit the value after adding.
  final int? defaultBeaconTypeId;

  /// Beacon attribute holding the default strength; null means the
  /// default comes from the beacon's `warfareBuff1-4` pair for
  /// [buffId] (native dbuff environments).
  final int? defaultAttrId;

  /// Static fallback default for buffs without a resolvable beacon
  /// (sovereignty upgrades, Triglavian, insurgency suppression).
  final double? staticDefault;
}

/// Buffs offered for free-form (custom) selection, in display order.
const systemBuffLibrary = <SystemBuffLibraryEntry>[
  SystemBuffLibraryEntry(
    buffId: -2001,
    zh: "护盾值加成（脉冲星）",
    en: "Shield Hitpoint Bonus (Pulsar)",
    defaultBeaconTypeId: 30844,
    defaultAttrId: 146,
  ),
  SystemBuffLibraryEntry(
    buffId: -2002,
    zh: "信号半径惩罚（脉冲星）",
    en: "Signature Radius Penalty (Pulsar)",
    defaultBeaconTypeId: 30844,
    defaultAttrId: 652,
  ),
  SystemBuffLibraryEntry(
    buffId: -2003,
    zh: "装甲抗性惩罚（脉冲星）",
    en: "Armor Resistance Penalty (Pulsar)",
    defaultBeaconTypeId: 30844,
    defaultAttrId: 1465,
  ),
  SystemBuffLibraryEntry(
    buffId: -2004,
    zh: "电容回充时间加成（脉冲星）",
    en: "Capacitor Recharge Time Bonus (Pulsar)",
    defaultBeaconTypeId: 30844,
    defaultAttrId: 1500,
  ),
  SystemBuffLibraryEntry(
    buffId: -2005,
    zh: "能量战强度加成（脉冲星）",
    en: "Energy Warfare Strength Bonus (Pulsar)",
    defaultBeaconTypeId: 30844,
    defaultAttrId: 1966,
  ),
  SystemBuffLibraryEntry(
    buffId: -2006,
    zh: "惯性惩罚（黑洞）",
    en: "Agility Penalty (Black Hole)",
    defaultBeaconTypeId: 30845,
    defaultAttrId: 169,
  ),
  SystemBuffLibraryEntry(
    buffId: -2007,
    zh: "锁定距离加成（黑洞）",
    en: "Targeting Range Bonus (Black Hole)",
    defaultBeaconTypeId: 30845,
    defaultAttrId: 237,
  ),
  SystemBuffLibraryEntry(
    buffId: -2008,
    zh: "导弹速度加成（黑洞）",
    en: "Missile Velocity Bonus (Black Hole)",
    defaultBeaconTypeId: 30845,
    defaultAttrId: 1469,
  ),
  SystemBuffLibraryEntry(
    buffId: -2009,
    zh: "最大速度加成（黑洞）",
    en: "Maximum Velocity Bonus (Black Hole)",
    defaultBeaconTypeId: 30845,
    defaultAttrId: 1470,
  ),
  SystemBuffLibraryEntry(
    buffId: -2010,
    zh: "导弹爆炸速度加成（黑洞）",
    en: "Missile Explosion Velocity Bonus (Black Hole)",
    defaultBeaconTypeId: 30845,
    defaultAttrId: 1483,
  ),
  SystemBuffLibraryEntry(
    buffId: -2011,
    zh: "停滞缠绕强度惩罚（黑洞）",
    en: "Stasis Webifier Strength Penalty (Black Hole)",
    defaultBeaconTypeId: 30845,
    defaultAttrId: 1969,
  ),
  SystemBuffLibraryEntry(
    buffId: -2012,
    zh: "装甲维修量惩罚（激变变星）",
    en: "Armor Repair Amount Penalty (Cataclysmic Variable)",
    defaultBeaconTypeId: 30846,
    defaultAttrId: 1495,
  ),
  SystemBuffLibraryEntry(
    buffId: -2013,
    zh: "护盾回充量惩罚（激变变星）",
    en: "Shield Boost Amount Penalty (Cataclysmic Variable)",
    defaultBeaconTypeId: 30846,
    defaultAttrId: 1496,
  ),
  SystemBuffLibraryEntry(
    buffId: -2014,
    zh: "远程护盾维修量加成（激变变星）",
    en: "Remote Shield Repair Amount Bonus (Cataclysmic Variable)",
    defaultBeaconTypeId: 30846,
    defaultAttrId: 1497,
  ),
  SystemBuffLibraryEntry(
    buffId: -2015,
    zh: "远程装甲维修量加成（激变变星）",
    en: "Remote Armor Repair Amount Bonus (Cataclysmic Variable)",
    defaultBeaconTypeId: 30846,
    defaultAttrId: 1498,
  ),
  SystemBuffLibraryEntry(
    buffId: -2016,
    zh: "电容容量加成（激变变星）",
    en: "Capacitor Capacity Bonus (Cataclysmic Variable)",
    defaultBeaconTypeId: 30846,
    defaultAttrId: 1499,
  ),
  SystemBuffLibraryEntry(
    buffId: -2017,
    zh: "电容回充时间惩罚（激变变星）",
    en: "Capacitor Recharge Time Penalty (Cataclysmic Variable)",
    defaultBeaconTypeId: 30846,
    defaultAttrId: 1500,
  ),
  SystemBuffLibraryEntry(
    buffId: -2018,
    zh: "远程电容传输量惩罚（激变变星）",
    en: "Remote Capacitor Transmitter Amount Penalty (Cataclysmic Variable)",
    defaultBeaconTypeId: 30846,
    defaultAttrId: 1840,
  ),
  SystemBuffLibraryEntry(
    buffId: -2019,
    zh: "锁定距离惩罚（磁星）",
    en: "Targeting Range Penalty (Magnetar)",
    defaultBeaconTypeId: 30847,
    defaultAttrId: 237,
  ),
  SystemBuffLibraryEntry(
    buffId: -2020,
    zh: "跟踪速度惩罚（磁星）",
    en: "Tracking Speed Penalty (Magnetar)",
    defaultBeaconTypeId: 30847,
    defaultAttrId: 244,
  ),
  SystemBuffLibraryEntry(
    buffId: -2021,
    zh: "伤害加成（磁星）",
    en: "Damage Bonus (Magnetar)",
    defaultBeaconTypeId: 30847,
    defaultAttrId: 1482,
  ),
  SystemBuffLibraryEntry(
    buffId: -2022,
    zh: "导弹爆炸半径惩罚（磁星）",
    en: "Missile Explosion Radius Penalty (Magnetar)",
    defaultBeaconTypeId: 30847,
    defaultAttrId: 1967,
  ),
  SystemBuffLibraryEntry(
    buffId: -2023,
    zh: "目标标记强度惩罚（磁星）",
    en: "Target Painter Strength Penalty (Magnetar)",
    defaultBeaconTypeId: 30847,
    defaultAttrId: 1968,
  ),
  SystemBuffLibraryEntry(
    buffId: -2024,
    zh: "装备热量伤害惩罚（红巨星）",
    en: "Module Heat Damage Penalty (Red Giant)",
    defaultBeaconTypeId: 30848,
    defaultAttrId: 1485,
  ),
  SystemBuffLibraryEntry(
    buffId: -2025,
    zh: "超载加成（红巨星）",
    en: "Overload Bonus (Red Giant)",
    defaultBeaconTypeId: 30848,
    defaultAttrId: 1486,
  ),
  SystemBuffLibraryEntry(
    buffId: -2026,
    zh: "立体炸弹范围加成（红巨星）",
    en: "Smart Bomb Range Bonus (Red Giant)",
    defaultBeaconTypeId: 30848,
    defaultAttrId: 1487,
  ),
  SystemBuffLibraryEntry(
    buffId: -2027,
    zh: "立体炸弹伤害加成（红巨星）",
    en: "Smart Bomb Damage Bonus (Red Giant)",
    defaultBeaconTypeId: 30848,
    defaultAttrId: 1488,
  ),
  SystemBuffLibraryEntry(
    buffId: -2028,
    zh: "炸弹伤害加成（红巨星）",
    en: "Bomb Damage Bonus (Red Giant)",
    defaultBeaconTypeId: 30848,
    defaultAttrId: 1488,
  ),
  SystemBuffLibraryEntry(
    buffId: -2029,
    zh: "装甲值加成（沃尔夫-拉叶星）",
    en: "Armor Hitpoint Bonus (Wolf Rayet)",
    defaultBeaconTypeId: 30849,
    defaultAttrId: 148,
  ),
  SystemBuffLibraryEntry(
    buffId: -2030,
    zh: "信号半径加成（沃尔夫-拉叶星）",
    en: "Signature Radius Bonus (Wolf Rayet)",
    defaultBeaconTypeId: 30849,
    defaultAttrId: 652,
  ),
  SystemBuffLibraryEntry(
    buffId: -2031,
    zh: "护盾抗性惩罚（沃尔夫-拉叶星）",
    en: "Shield Resistance Penalty (Wolf Rayet)",
    defaultBeaconTypeId: 30849,
    defaultAttrId: 1489,
  ),
  SystemBuffLibraryEntry(
    buffId: -2032,
    zh: "小型武器伤害加成（沃尔夫-拉叶星）",
    en: "Small Weapon Damage Bonus (Wolf Rayet)",
    defaultBeaconTypeId: 30849,
    defaultAttrId: 1493,
  ),
  SystemBuffLibraryEntry(
    buffId: -2101,
    zh: "电磁抗性惩罚（电子风暴）",
    en: "EM Resistance Penalty (Electrical Storm)",
    defaultBeaconTypeId: 56064,
    defaultAttrId: 984,
  ),
  SystemBuffLibraryEntry(
    buffId: -2102,
    zh: "电容回充时间加成（电子风暴）",
    en: "Capacitor Recharge Time Bonus (Electrical Storm)",
    defaultBeaconTypeId: 56064,
    defaultAttrId: 1500,
  ),
  SystemBuffLibraryEntry(
    buffId: -2103,
    zh: "动能抗性惩罚（异种物质风暴）",
    en: "Kinetic Resistance Penalty (Exotic Matter Storm)",
    defaultBeaconTypeId: 56058,
    defaultAttrId: 986,
  ),
  SystemBuffLibraryEntry(
    buffId: -2104,
    zh: "装甲维修周期加成（异种物质风暴）",
    en: "Armor Repair Duration Bonus (Exotic Matter Storm)",
    defaultBeaconTypeId: 56058,
    defaultAttrId: 3098,
  ),
  SystemBuffLibraryEntry(
    buffId: -2105,
    zh: "护盾回充周期加成（异种物质风暴）",
    en: "Shield Booster Duration Bonus (Exotic Matter Storm)",
    defaultBeaconTypeId: 56058,
    defaultAttrId: 3099,
  ),
  SystemBuffLibraryEntry(
    buffId: -2106,
    zh: "采矿周期加成（异种物质风暴）",
    en: "Mining Duration Bonus (Exotic Matter Storm)",
    defaultBeaconTypeId: 56058,
    defaultAttrId: 203,
  ),
  SystemBuffLibraryEntry(
    buffId: -2107,
    zh: "跃迁速度加成（异种物质风暴）",
    en: "Warp Speed Bonus (Exotic Matter Storm)",
    defaultBeaconTypeId: 56058,
    defaultAttrId: 601,
  ),
  SystemBuffLibraryEntry(
    buffId: -2108,
    zh: "扫描分辨率加成（异种物质风暴）",
    en: "Scan Resolution Bonus (Exotic Matter Storm)",
    defaultBeaconTypeId: 56058,
    defaultAttrId: 566,
  ),
  SystemBuffLibraryEntry(
    buffId: -2109,
    zh: "爆炸抗性惩罚（伽玛射线风暴）",
    en: "Explosive Resistance Penalty (Gamma Ray Storm)",
    defaultBeaconTypeId: 56060,
    defaultAttrId: 985,
  ),
  SystemBuffLibraryEntry(
    buffId: -2110,
    zh: "远程护盾维修量惩罚（伽玛射线风暴）",
    en: "Remote Shield Repair Amount Penalty (Gamma Ray Storm)",
    defaultBeaconTypeId: 56060,
    defaultAttrId: 1497,
  ),
  SystemBuffLibraryEntry(
    buffId: -2111,
    zh: "远程装甲维修量惩罚（伽玛射线风暴）",
    en: "Remote Armor Repair Amount Penalty (Gamma Ray Storm)",
    defaultBeaconTypeId: 56060,
    defaultAttrId: 1498,
  ),
  SystemBuffLibraryEntry(
    buffId: -2112,
    zh: "护盾值加成（伽玛射线风暴）",
    en: "Shield Hitpoint Bonus (Gamma Ray Storm)",
    defaultBeaconTypeId: 56060,
    defaultAttrId: 146,
  ),
  SystemBuffLibraryEntry(
    buffId: -2113,
    zh: "电容容量加成（伽玛射线风暴）",
    en: "Capacitor Capacity Bonus (Gamma Ray Storm)",
    defaultBeaconTypeId: 56060,
    defaultAttrId: 1499,
  ),
  SystemBuffLibraryEntry(
    buffId: -2114,
    zh: "信号半径加成（伽玛射线风暴）",
    en: "Signature Radius Bonus (Gamma Ray Storm)",
    defaultBeaconTypeId: 56060,
    defaultAttrId: 652,
  ),
  SystemBuffLibraryEntry(
    buffId: -2115,
    zh: "热能抗性惩罚（等离子火焰风暴）",
    en: "Thermal Resistance Penalty (Plasma Firestorm)",
    defaultBeaconTypeId: 56062,
    defaultAttrId: 987,
  ),
  SystemBuffLibraryEntry(
    buffId: -2116,
    zh: "伤害加成（等离子火焰风暴）",
    en: "Damage Bonus (Plasma Firestorm)",
    defaultBeaconTypeId: 56062,
    defaultAttrId: 1482,
  ),
  SystemBuffLibraryEntry(
    buffId: -2117,
    zh: "跟踪速度惩罚（等离子火焰风暴）",
    en: "Tracking Speed Penalty (Plasma Firestorm)",
    defaultBeaconTypeId: 56062,
    defaultAttrId: 244,
  ),
  SystemBuffLibraryEntry(
    buffId: -2118,
    zh: "爆炸半径惩罚（等离子火焰风暴）",
    en: "Explosion Radius Penalty (Plasma Firestorm)",
    defaultBeaconTypeId: 56062,
    defaultAttrId: 1967,
  ),
  SystemBuffLibraryEntry(
    buffId: -2119,
    zh: "装甲值加成（等离子火焰风暴）",
    en: "Armor Hitpoint Bonus (Plasma Firestorm)",
    defaultBeaconTypeId: 56062,
    defaultAttrId: 148,
  ),
  SystemBuffLibraryEntry(
    buffId: -2120,
    zh: "热能抗性加成（不稳定冰风暴）",
    en: "Thermal Resistance Bonus (Volatile Ice Storm)",
    defaultBeaconTypeId: 56997,
    defaultAttrId: 987,
  ),
  SystemBuffLibraryEntry(
    buffId: -2121,
    zh: "装备热量伤害加成（不稳定冰风暴）",
    en: "Module Heat Damage Bonus (Volatile Ice Storm)",
    defaultBeaconTypeId: 56997,
    defaultAttrId: 1229,
  ),
  SystemBuffLibraryEntry(
    buffId: 90,
    zh: "电磁抗性惩罚",
    en: "EM Resistance Penalty",
    defaultBeaconTypeId: 47381,
  ),
  SystemBuffLibraryEntry(
    buffId: 92,
    zh: "电容回充加成",
    en: "Capacitor Recharge Bonus",
    defaultBeaconTypeId: 47381,
  ),
  SystemBuffLibraryEntry(
    buffId: 93,
    zh: "爆炸抗性惩罚",
    en: "Explosive Resistance Penalty",
    defaultBeaconTypeId: 47387,
  ),
  SystemBuffLibraryEntry(
    buffId: 94,
    zh: "护盾值加成",
    en: "Shield HP Bonus",
    defaultBeaconTypeId: 47387,
  ),
  SystemBuffLibraryEntry(
    buffId: 95,
    zh: "热能抗性惩罚",
    en: "Thermal Resistance Penalty",
    defaultBeaconTypeId: 47390,
  ),
  SystemBuffLibraryEntry(buffId: 96, zh: "装甲值加成", en: "Armor HP Bonus", defaultBeaconTypeId: 47390),
  SystemBuffLibraryEntry(
    buffId: 97,
    zh: "炮台射程惩罚",
    en: "Turret Optimal and Falloff Range Penalty",
    defaultBeaconTypeId: 47378,
  ),
  SystemBuffLibraryEntry(buffId: 98, zh: "速度加成", en: "Velocity Bonus", defaultBeaconTypeId: 47378),
  SystemBuffLibraryEntry(
    buffId: 99,
    zh: "动能抗性惩罚",
    en: "Kinetic Resistance Penalty",
    defaultBeaconTypeId: 47384,
  ),
  SystemBuffLibraryEntry(
    buffId: 100,
    zh: "扫描分辨率加成",
    en: "Scan Resolution Bonus",
    defaultBeaconTypeId: 47384,
  ),
  SystemBuffLibraryEntry(buffId: 2433, zh: "护盾值加成", en: "Shield Hitpoint Bonus", staticDefault: 1),
  SystemBuffLibraryEntry(
    buffId: 2434,
    zh: "电容容量加成",
    en: "Capacitor Capacity Bonus",
    staticDefault: 1,
  ),
  SystemBuffLibraryEntry(
    buffId: 2441,
    zh: "本地护盾回充加成",
    en: "Local Shield Booster Bonus",
    staticDefault: 1,
  ),
  SystemBuffLibraryEntry(
    buffId: 2442,
    zh: "本地装甲维修加成",
    en: "Local Armor Repairer Bonus",
    staticDefault: 1,
  ),
  SystemBuffLibraryEntry(buffId: 2435, zh: "装甲值加成", en: "Armor Hitpoint Bonus", staticDefault: 1),
  SystemBuffLibraryEntry(buffId: 2436, zh: "装备超载加成", en: "Module Overload Bonus", staticDefault: 1),
  SystemBuffLibraryEntry(
    buffId: 2437,
    zh: "电容回充加成",
    en: "Capacitor Recharge Bonus",
    staticDefault: 1,
  ),
  SystemBuffLibraryEntry(
    buffId: 2438,
    zh: "锁定与定向扫描距离加成",
    en: "Targeting and DScan Range Bonus",
    staticDefault: 1,
  ),
  SystemBuffLibraryEntry(
    buffId: 2440,
    zh: "基础跃迁速度增加",
    en: "Base Warp Speed Addition",
    staticDefault: 1,
  ),
  SystemBuffLibraryEntry(
    buffId: 2439,
    zh: "扫描分辨率加成",
    en: "Scan Resolution Bonus",
    staticDefault: 1,
  ),
  SystemBuffLibraryEntry(
    buffId: 2534,
    zh: "最大锁定数惩罚",
    en: "Maximum Locked Targets Penalty",
    staticDefault: 1,
  ),
  SystemBuffLibraryEntry(buffId: 2535, zh: "跃迁速度惩罚", en: "Warp Speed Penalty", staticDefault: 1),
  SystemBuffLibraryEntry(
    buffId: 2538,
    zh: "远程装甲维修加成",
    en: "Remote Armor Repair Bonus",
    staticDefault: 1,
  ),
  SystemBuffLibraryEntry(
    buffId: 2539,
    zh: "远程护盾维修加成",
    en: "Remote Shield Boost Bonus",
    staticDefault: 1,
  ),
  SystemBuffLibraryEntry(
    buffId: 2405,
    zh: "停滞缠绕与跃迁扰断距离加成",
    en: "Webifier and Scrambler Range Bonus (Anti-Pirate)",
    staticDefault: 1,
  ),
  SystemBuffLibraryEntry(
    buffId: 79,
    zh: "信号半径惩罚",
    en: "Signature Radius Penalty",
    defaultBeaconTypeId: 47439,
  ),
  SystemBuffLibraryEntry(buffId: 80, zh: "惯性加成", en: "Inertia Bonus", defaultBeaconTypeId: 47436),
  SystemBuffLibraryEntry(
    buffId: 81,
    zh: "最大速度加成",
    en: "Max Velocity Bonus",
    defaultBeaconTypeId: 47436,
  ),
  SystemBuffLibraryEntry(
    buffId: 88,
    zh: "护盾回充量惩罚",
    en: "Shield Booster Amount Penalty",
    defaultBeaconTypeId: 47620,
  ),
  SystemBuffLibraryEntry(
    buffId: 89,
    zh: "护盾回充周期加成",
    en: "Shield Booster Duration Bonus",
    defaultBeaconTypeId: 47620,
  ),
];

/// Custom-buff library lookup by buff id.
final systemBuffLibraryById = <int, SystemBuffLibraryEntry>{
  for (final entry in systemBuffLibrary) entry.buffId: entry,
};
