// Automatically generated by `lib.codegen.dogma_unit_id.codegen_dart`
// DO NOT EDIT

part of "eve.dart";

enum EveDogmaUnitId {
  /// - ID: 1
  /// - Name: Length
  length(1),

  /// - ID: 2
  /// - Name: Mass
  mass(2),

  /// - ID: 3
  /// - Name: Time
  time(3),

  /// - ID: 4
  /// - Name: Electric Current
  electricCurrent(4),

  /// - ID: 5
  /// - Name: Temperature
  temperature(5),

  /// - ID: 6
  /// - Name: Amount Of Substance
  amountOfSubstance(6),

  /// - ID: 7
  /// - Name: Luminous Intensity
  luminousIntensity(7),

  /// - ID: 8
  /// - Name: Area
  area(8),

  /// - ID: 9
  /// - Name: Volume
  volume(9),

  /// - ID: 10
  /// - Name: Speed
  speed(10),

  /// - ID: 11
  /// - Name: Acceleration
  acceleration(11),

  /// - ID: 12
  /// - Name: Wave Number
  waveNumber(12),

  /// - ID: 13
  /// - Name: Mass Density
  massDensity(13),

  /// - ID: 14
  /// - Name: Specific Volume
  specificVolume(14),

  /// - ID: 15
  /// - Name: Current Density
  currentDensity(15),

  /// - ID: 16
  /// - Name: Magnetic Field Strength
  magneticFieldStrength(16),

  /// - ID: 17
  /// - Name: Amount-Of-Substance Concentration
  amountOfSubstanceConcentration(17),

  /// - ID: 18
  /// - Name: Luminance
  luminance(18),

  /// - ID: 19
  /// - Name: Mass Fraction
  massFraction(19),

  /// - ID: 101
  /// - Name: Milliseconds
  milliseconds(101),

  /// - ID: 102
  /// - Name: Millimeters
  millimeters(102),

  /// - ID: 103
  /// - Name: MegaPascals
  megaPascals(103),

  /// - ID: 104
  /// - Name: Multiplier
  multiplier(104),

  /// - ID: 105
  /// - Name: Percentage
  percentage(105),

  /// - ID: 106
  /// - Name: Teraflops
  teraflops(106),

  /// - ID: 107
  /// - Name: MegaWatts
  megaWatts(107),

  /// - ID: 108
  /// - Name: Inverse Absolute Percent
  inverseAbsolutePercent(108),

  /// - ID: 109
  /// - Name: Modifier Percent
  modifierPercent(109),

  /// - ID: 111
  /// - Name: Inversed Modifier Percent
  inversedModifierPercent(111),

  /// - ID: 112
  /// - Name: Radians/Second
  radiansSecond(112),

  /// - ID: 113
  /// - Name: Hitpoints
  hitpoints(113),

  /// - ID: 114
  /// - Name: capacitor units
  capacitorUnits(114),

  /// - ID: 115
  /// - Name: groupID
  groupId(115),

  /// - ID: 116
  /// - Name: typeID
  typeId(116),

  /// - ID: 117
  /// - Name: Sizeclass
  sizeclass(117),

  /// - ID: 118
  /// - Name: Ore units
  oreUnits(118),

  /// - ID: 119
  /// - Name: attributeID
  attributeId(119),

  /// - ID: 120
  /// - Name: attributePoints
  attributePoints(120),

  /// - ID: 121
  /// - Name: realPercent
  realPercent(121),

  /// - ID: 122
  /// - Name: Fitting slots
  fittingSlots(122),

  /// - ID: 123
  /// - Name: trueTime
  trueTime(123),

  /// - ID: 124
  /// - Name: Modifier Relative Percent
  modifierRelativePercent(124),

  /// - ID: 125
  /// - Name: Newton
  newton(125),

  /// - ID: 126
  /// - Name: Light Year
  lightYear(126),

  /// - ID: 127
  /// - Name: Absolute Percent
  absolutePercent(127),

  /// - ID: 128
  /// - Name: Drone bandwidth
  droneBandwidth(128),

  /// - ID: 129
  /// - Name: Hours
  hours(129),

  /// - ID: 133
  /// - Name: Money
  money(133),

  /// - ID: 134
  /// - Name: Logistical Capacity
  logisticalCapacity(134),

  /// - ID: 135
  /// - Name: Astronomical Unit
  astronomicalUnit(135),

  /// - ID: 136
  /// - Name: Slot
  slot(136),

  /// - ID: 137
  /// - Name: Boolean
  boolean(137),

  /// - ID: 138
  /// - Name: Units
  units(138),

  /// - ID: 139
  /// - Name: Bonus
  bonus(139),

  /// - ID: 140
  /// - Name: Level
  level(140),

  /// - ID: 141
  /// - Name: Hardpoints
  hardpoints(141),

  /// - ID: 142
  /// - Name: Sex
  sex(142),

  /// - ID: 143
  /// - Name: Datetime
  datetime(143),

  /// - ID: 144
  /// - Name: Warp speed
  warpSpeed(144),

  /// - ID: 205
  /// - Name: modifier realPercent
  modifierRealPercent(205);

  const EveDogmaUnitId(this.id);

  final int id;

  static const Map<int, EveDogmaUnitId> byId = <int, EveDogmaUnitId>{
    1: EveDogmaUnitId.length,
    2: EveDogmaUnitId.mass,
    3: EveDogmaUnitId.time,
    4: EveDogmaUnitId.electricCurrent,
    5: EveDogmaUnitId.temperature,
    6: EveDogmaUnitId.amountOfSubstance,
    7: EveDogmaUnitId.luminousIntensity,
    8: EveDogmaUnitId.area,
    9: EveDogmaUnitId.volume,
    10: EveDogmaUnitId.speed,
    11: EveDogmaUnitId.acceleration,
    12: EveDogmaUnitId.waveNumber,
    13: EveDogmaUnitId.massDensity,
    14: EveDogmaUnitId.specificVolume,
    15: EveDogmaUnitId.currentDensity,
    16: EveDogmaUnitId.magneticFieldStrength,
    17: EveDogmaUnitId.amountOfSubstanceConcentration,
    18: EveDogmaUnitId.luminance,
    19: EveDogmaUnitId.massFraction,
    101: EveDogmaUnitId.milliseconds,
    102: EveDogmaUnitId.millimeters,
    103: EveDogmaUnitId.megaPascals,
    104: EveDogmaUnitId.multiplier,
    105: EveDogmaUnitId.percentage,
    106: EveDogmaUnitId.teraflops,
    107: EveDogmaUnitId.megaWatts,
    108: EveDogmaUnitId.inverseAbsolutePercent,
    109: EveDogmaUnitId.modifierPercent,
    111: EveDogmaUnitId.inversedModifierPercent,
    112: EveDogmaUnitId.radiansSecond,
    113: EveDogmaUnitId.hitpoints,
    114: EveDogmaUnitId.capacitorUnits,
    115: EveDogmaUnitId.groupId,
    116: EveDogmaUnitId.typeId,
    117: EveDogmaUnitId.sizeclass,
    118: EveDogmaUnitId.oreUnits,
    119: EveDogmaUnitId.attributeId,
    120: EveDogmaUnitId.attributePoints,
    121: EveDogmaUnitId.realPercent,
    122: EveDogmaUnitId.fittingSlots,
    123: EveDogmaUnitId.trueTime,
    124: EveDogmaUnitId.modifierRelativePercent,
    125: EveDogmaUnitId.newton,
    126: EveDogmaUnitId.lightYear,
    127: EveDogmaUnitId.absolutePercent,
    128: EveDogmaUnitId.droneBandwidth,
    129: EveDogmaUnitId.hours,
    133: EveDogmaUnitId.money,
    134: EveDogmaUnitId.logisticalCapacity,
    135: EveDogmaUnitId.astronomicalUnit,
    136: EveDogmaUnitId.slot,
    137: EveDogmaUnitId.boolean,
    138: EveDogmaUnitId.units,
    139: EveDogmaUnitId.bonus,
    140: EveDogmaUnitId.level,
    141: EveDogmaUnitId.hardpoints,
    142: EveDogmaUnitId.sex,
    143: EveDogmaUnitId.datetime,
    144: EveDogmaUnitId.warpSpeed,
    205: EveDogmaUnitId.modifierRealPercent,
  };

  static EveDogmaUnitId? fromId(int id) => byId[id];
}
