// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:collection/collection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `has_charge`, `validate_charge`

int get attrVolume =>
    RustLib.instance.api.crateApiValidatePostValidateChargeAttrVolume();

int get attrChargeSize =>
    RustLib.instance.api.crateApiValidatePostValidateChargeAttrChargeSize();

int get attrAmmoCap =>
    RustLib.instance.api.crateApiValidatePostValidateChargeAttrAmmoCap();

I32Array5 get attrChargeGroups =>
    RustLib.instance.api.crateApiValidatePostValidateChargeAttrChargeGroups();

class I32Array5 extends NonGrowableListView<int> {
  static const arraySize = 5;

  @internal
  Int32List get inner => _inner;
  final Int32List _inner;

  I32Array5(this._inner)
      : assert(_inner.length == arraySize),
        super(_inner);

  I32Array5.init() : this(Int32List(arraySize));
}
