/// Flutter icons ExternalIcon
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ExternalIcon
///      fonts:
///       - asset: fonts/ExternalIcon.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
library;

import 'package:flutter/material.dart';

class ExternalIcon {
  ExternalIcon._();

  static const _kFontFam = 'ExternalIcon';
  static const String? _kFontPkg = null;

  static const IconData cubes = IconData(0xf1b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
