// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            // These functions are ignored because they are not marked as `pub`: `calculate`


            

            
                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EveDatabase>>
                abstract class EveDatabase implements RustOpaqueInterface {
                    static Future<EveDatabase>  init({required List<int> dogmaAttrBuffer , required List<int> dogmaEffectBuffer , required List<int> typeDogmaBuffer , required List<int> typesBuffer })=>RustLib.instance.api.crateApiDataEveDatabaseInit(dogmaAttrBuffer: dogmaAttrBuffer, dogmaEffectBuffer: dogmaEffectBuffer, typeDogmaBuffer: typeDogmaBuffer, typesBuffer: typesBuffer);



                    
                }
                
            