# Usage: source scripts/setup-android-sdk.sh
# Expects these env vars from the Nix android shell:
#   NIX_ANDROID_SDK_ROOT
#   JAVA_HOME
#   flutter (path to flutter SDK)
# Optionally:
#   ANDROID_SDK_ROOT, ANDROID_HOME, ANDROID_NDK_ROOT, NDK_HOME
#   (set by the Nix shellHook from nix expression values)

setup_android_shim() {
  local host_sdk="$HOME/Android/Sdk"
  local sdk_shim="$PWD/.direnv/android-sdk"

  if [ ! -x "$host_sdk/emulator/emulator" ]; then
    export ANDROID_SDK_ROOT="$NIX_ANDROID_SDK_ROOT"
    export ANDROID_HOME="$NIX_ANDROID_SDK_ROOT"
    return 0
  fi

  mkdir -p "$sdk_shim/emulator"
  ln -sfn "$NIX_ANDROID_SDK_ROOT/build-tools" "$sdk_shim/build-tools"
  ln -sfn "$NIX_ANDROID_SDK_ROOT/cmake" "$sdk_shim/cmake"
  ln -sfn "$NIX_ANDROID_SDK_ROOT/cmdline-tools" "$sdk_shim/cmdline-tools"
  ln -sfn "$NIX_ANDROID_SDK_ROOT/licenses" "$sdk_shim/licenses"
  ln -sfn "$NIX_ANDROID_SDK_ROOT/ndk" "$sdk_shim/ndk"
  ln -sfn "$NIX_ANDROID_SDK_ROOT/ndk-bundle" "$sdk_shim/ndk-bundle"
  ln -sfn "$NIX_ANDROID_SDK_ROOT/platform-tools" "$sdk_shim/platform-tools"
  ln -sfn "$NIX_ANDROID_SDK_ROOT/platforms" "$sdk_shim/platforms"
  ln -sfn "$NIX_ANDROID_SDK_ROOT/tools" "$sdk_shim/tools"
  ln -sfn "$host_sdk/system-images" "$sdk_shim/system-images"

  export ANDROID_SDK_ROOT="$sdk_shim"
  export ANDROID_HOME="$sdk_shim"
}

setup_aapt2() {
  local aapt2_path
  aapt2_path="$(echo "$NIX_ANDROID_SDK_ROOT/build-tools/"*"/aapt2" 2>/dev/null)"
  if [ -n "$aapt2_path" ] && [ -x "$aapt2_path" ]; then
    export GRADLE_OPTS="-Dorg.gradle.project.android.aapt2FromMavenOverride=$aapt2_path${GRADLE_OPTS:+ $GRADLE_OPTS}"
  fi
}

setup_cmake_path() {
  local cmake_root
  cmake_root="$(echo "$NIX_ANDROID_SDK_ROOT/cmake/"*/ 2>/dev/null)"
  if [ -n "$cmake_root" ] && [ -d "$cmake_root" ]; then
    cmake_root="${cmake_root%/}"
    export PATH="$cmake_root/bin:$PATH"
  fi
}

generate_local_properties() {
  local cmake_root
  cmake_root="$(echo "$NIX_ANDROID_SDK_ROOT/cmake/"*/ 2>/dev/null)"
  cmake_root="${cmake_root%/}"

  local cmake_basename
  cmake_basename="$(basename "$cmake_root" 2>/dev/null)"

  local marker="# Generated by nix develop from flake.nix"
  # The Flutter app lives in apps/eve-fit-assistant; anchor to the repo root
  # (this script's parent dir) instead of the caller's working directory.
  local repo_root
  repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
  local props="$repo_root/apps/eve-fit-assistant/android/local.properties"

  if [ ! -f "$props" ] \
    || ! grep -Fqx "$marker" "$props" \
    || ! grep -Fqx "sdk.dir=$ANDROID_SDK_ROOT" "$props"; then
    {
      printf '%s\n' \
        "$marker" \
        "flutter.sdk=${flutter}" \
        "sdk.dir=$ANDROID_SDK_ROOT" \
        "ndk.dir=$ANDROID_SDK_ROOT/ndk-bundle" \
        "cmake.dir=$ANDROID_SDK_ROOT/cmake/$cmake_basename"
    } > "$props"
  fi
}

setup_android_shim
setup_aapt2
setup_cmake_path
generate_local_properties
