from __future__ import annotations

import json

from typing import TYPE_CHECKING

import bootstrap.config

from bootstrap.constant import EVE_ATTR_OUT_PATH


if TYPE_CHECKING:
    from pathlib import Path


def codegen_dart() -> list[Path]:
    bootstrap.config.DeveloperConfiguration.ensure_loaded()
    attrs_path = bootstrap.config.DEV_CONFIGURATION.codegen.attr_id_source
    if attrs_path is None:
        return []

    out_file = EVE_ATTR_OUT_PATH
    out_file.parent.mkdir(exist_ok=True, parents=True)

    with open(attrs_path, "r", encoding="utf-8") as f:
        native_attrs = json.load(f)

    with open(out_file, "w+", encoding="utf-8") as f:
        f.write(
            "// Automatically generated by `lib.codegen.attr_id.codegen_dart`\n"
            "// DO NOT EDIT\n\n"
            'part of "eve.dart";\n'
        )

        f.write("class EveConstExtendedAttrID {\n")

        for key, value in native_attrs["entries"].items():
            if int(key) >= 0:
                continue

            f.write(f"  /// - Name: {value['name']}\n")
            f.write(f"  /// - High is good: {value['highIsGood']}\n")
            f.write(f"  static const int {value['name']} = {key};\n")

        f.write("}\n\n")

    return [out_file]
