"""
Generates the Dart resource-resolution vocabulary constants.

The emitted file is the app-side mirror of the ``[resolution]`` table in
``efa.config.toml`` (see ``bootstrap.config.ResolutionVocabulary``): the
strings the app and the data pipeline must agree on — the resource-id scheme,
the legacy combined localization database id, the per-locale database prefix,
the static images prefix, and the resolution-context placeholder.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import bootstrap.config

from bootstrap.constant import DART_ROOT


if TYPE_CHECKING:
    from pathlib import Path


OUT_PATH = DART_ROOT / "constant" / "resource_vocabulary.g.dart"


def codegen_dart() -> list[Path]:
    bootstrap.config.ProjectConfiguration.ensure_loaded()
    assert bootstrap.config.CONFIGURATION is not None
    vocab = bootstrap.config.CONFIGURATION.resolution

    legacy_db_id = f"{vocab.scheme}{vocab.legacy_localization_db}"
    locales_prefix = f"{vocab.scheme}{vocab.localization_locales_prefix}"
    images_prefix = f"{vocab.scheme}{vocab.static_images_prefix}"
    placeholder = "{" + vocab.locale_placeholder + "}"
    locale_db_pattern = f"{locales_prefix}{placeholder}.db"

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUT_PATH.open("w", encoding="utf-8") as f:
        f.write(
            "// Automatically generated by `bootstrap.data.codegen.resource_vocabulary.codegen_dart`\n"
            "// DO NOT EDIT\n\n"
            "/// URI scheme prefix of checkout resource ids.\n"
            f'const String kResourceIdScheme = "{vocab.scheme}";\n\n'
            "/// Path (relative to `resource://`) of the legacy combined\n"
            "/// localization database.\n"
            f'const String kLegacyLocalizationDbPath = "{vocab.legacy_localization_db}";\n\n'
            "/// Resource id of the legacy combined localization database.\n"
            f'const String kLegacyLocalizationDbResourceId = "{legacy_db_id}";\n\n'
            "/// Path prefix (relative to `resource://`) of the per-locale\n"
            "/// localization databases.\n"
            "const String kLocalizationLocalesPathPrefix = "
            f'"{vocab.localization_locales_prefix}";\n\n'
            "/// Resource-id prefix of the per-locale localization databases.\n"
            f'const String kLocalizationLocalesResourcePrefix = "{locales_prefix}";\n\n'
            "/// Path prefix (relative to `resource://`) of the static image\n"
            "/// resources.\n"
            f'const String kStaticImagesPathPrefix = "{vocab.static_images_prefix}";\n\n'
            "/// Resource-id prefix of the static image resources.\n"
            f'const String kStaticImagesResourcePrefix = "{images_prefix}";\n\n'
            "/// Resolution-context placeholder embedded in resource-id patterns.\n"
            f'const String kLocalePlaceholder = "{placeholder}";\n\n'
            "/// Resource-id pattern of the per-locale localization database for\n"
            "/// the resolution context's locale.\n"
            "const String kLocaleLocalizationDbResourcePattern = "
            f'"{locale_db_pattern}";\n'
        )
    return [OUT_PATH]
