from __future__ import annotations

from typing import TYPE_CHECKING

import bootstrap.config

from bootstrap.constant import DART_ROOT


if TYPE_CHECKING:
    from pathlib import Path


OUT_PATH = DART_ROOT / "storage" / "repo" / "repo_version.dart"


def codegen_dart() -> list[Path]:
    bootstrap.config.ProjectConfiguration.ensure_loaded()
    schema = bootstrap.config.CONFIGURATION.version.data_schema

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUT_PATH.open("w", encoding="utf-8") as f:
        f.write(
            "// Automatically generated by `lib.codegen.schema_version.codegen_dart`\n"
            "// DO NOT EDIT\n\n"
            f"const int currentSchemaVersion = {schema};\n"
        )
    return [OUT_PATH]
