// Automatically generated by `lib.codegen.bundle_schema.codegen_dart`
// DO NOT EDIT

import "package:fast_immutable_collections/fast_immutable_collections.dart";

const int currentBundleSchemaVersion = 1;
final IList<int> supportedBundleSchemaVersions = IList([1]);
