name: Update Raw EVE Data (test)

permissions:
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches: [dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    name: Check and update raw data
    if: |
      (
        contains(github.event.pull_request.labels.*.name, 'D-Full CI') ||
        contains(github.event.pull_request.labels.*.name, 'D-CI-Data Update')
      ) &&
      github.repository == 'Embers-of-the-Fire/eve-fit-assistant' &&
      github.event.repository.fork == false
    uses: ./.github/workflows/_update-raw-data.yml
    secrets: inherit
    with:
      all: true
      no_upload: true